### ISSUE TITLE
TemplateDoesNotExist: admin/breadcrumbs.html

### ISSUE THREAD

**Issue by imdario** [geex-arts/django-jet#100]
I updated from Django JET 0.1.4 (with Django 1.9.7) to JET 0.9.0 (Django 1.10) and I get this error:

> Environment:
> 
> 
> Request Method: POST
> Request URL: http://127.0.0.1:8000/admin/manager/devices/2/
> 
> Django Version: 1.10
> Python Version: 2.7.9
> Installed Applications:
> ['manager',
>  'jet.dashboard',
>  'jet',
>  'django.contrib.admin',
>  'django.contrib.auth',
>  'django.contrib.contenttypes',
>  'django.contrib.sessions',
>  'django.contrib.messages',
>  'django.contrib.staticfiles']
> Installed Middleware:
> ['django.middleware.security.SecurityMiddleware',
>  'django.contrib.sessions.middleware.SessionMiddleware',
>  'django.middleware.common.CommonMiddleware',
>  'django.middleware.csrf.CsrfViewMiddleware',
>  'django.contrib.auth.middleware.AuthenticationMiddleware',
>  'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
>  'django.contrib.messages.middleware.MessageMiddleware',
>  'django.middleware.clickjacking.XFrameOptionsMiddleware']
> 
> Template loader postmortem
> Django tried loading these templates, in this order:
> 
> Using engine django:
>     * django.template.loaders.app_directories.Loader: D:\Workspace\DeviceManager\dm-web\manager\templates\admin\breadcrumbs.html (Source does not exist)
>     * django.template.loaders.app_directories.Loader: d:\Workspace\DeviceManager\dm-web\.env\lib\site-packages\jet\dashboard\templates\admin\breadcrumbs.html (Source does not exist)
>     * django.template.loaders.app_directories.Loader: d:\Workspace\DeviceManager\dm-web\.env\lib\site-packages\jet\templates\admin\breadcrumbs.html (Source does not exist)
>     * django.template.loaders.app_directories.Loader: d:\Workspace\DeviceManager\dm-web\.env\lib\site-packages\django\contrib\admin\templates\admin\breadcrumbs.html (Source does not exist)
>     * django.template.loaders.app_directories.Loader: d:\Workspace\DeviceManager\dm-web\.env\lib\site-packages\django\contrib\auth\templates\admin\breadcrumbs.html (Source does not exist)
> 
> 
> Template error:
> In template D:\Workspace\DeviceManager\dm-web\manager\templates\manager\view_device.html, error at line 0
>    admin/breadcrumbs.html   1 : {% extends "admin/change_form.html" %}
>    2 : {% load i18n admin_urls static admin_modify manager_tags %}
>    3 : 
>    4 : {% block extrahead %}{{ block.super }}
>    5 : <script type="text/javascript" src="{% static 'js/plotly.min.js' %}"></script>
>    6 : {% endblock %}
>    7 : 
>    8 : {% if not is_popup %}
>    9 : {% block breadcrumbs %}
>    10 : <div class="breadcrumbs">
> 
> 
> Traceback:
> 
> File "d:\Workspace\DeviceManager\dm-web\.env\lib\site-packages\django\core\handlers\exception.py" in inner
>   39.             response = get_response(request)
> 
> File "d:\Workspace\DeviceManager\dm-web\.env\lib\site-packages\django\core\handlers\base.py" in _legacy_get_response
>   249.             response = self._get_response(request)
> 
> File "d:\Workspace\DeviceManager\dm-web\.env\lib\site-packages\django\core\handlers\base.py" in _get_response
>   187.                 response = self.process_exception_by_middleware(e, request)
> 
> File "d:\Workspace\DeviceManager\dm-web\.env\lib\site-packages\django\core\handlers\base.py" in _get_response
>   185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)
> 
> File "d:\Workspace\DeviceManager\dm-web\.env\lib\site-packages\django\utils\decorators.py" in _wrapped_view
>   149.                     response = view_func(request, *args, **kwargs)
> 
> File "d:\Workspace\DeviceManager\dm-web\.env\lib\site-packages\django\views\decorators\cache.py" in _wrapped_view_func
>   57.         response = view_func(request, *args, **kwargs)
> 
> File "d:\Workspace\DeviceManager\dm-web\.env\lib\site-packages\django\contrib\admin\sites.py" in inner
>   211.             return view(request, *args, **kwargs)
> 
> File "D:\Workspace\DeviceManager\dm-web\manager\admin.py" in show_view
>   240.                                   RequestContext(request))
> 
> File "d:\Workspace\DeviceManager\dm-web\.env\lib\site-packages\django\shortcuts.py" in render_to_response
>   21.     content = loader.render_to_string(template_name, context, using=using)
> 
> File "d:\Workspace\DeviceManager\dm-web\.env\lib\site-packages\django\template\loader.py" in render_to_string
>   68.     return template.render(context, request)
> 
> File "d:\Workspace\DeviceManager\dm-web\.env\lib\site-packages\django\template\backends\django.py" in render
>   68.             reraise(exc, self.backend)
> 
> File "d:\Workspace\DeviceManager\dm-web\.env\lib\site-packages\django\template\backends\django.py" in reraise
>   89.     six.reraise(exc.__class__, new, sys.exc_info()[2])
> 
> File "d:\Workspace\DeviceManager\dm-web\.env\lib\site-packages\django\template\backends\django.py" in render
>   66.             return self.template.render(context)
> 
> File "d:\Workspace\DeviceManager\dm-web\.env\lib\site-packages\django\template\base.py" in render
>   208.                     return self._render(context)
> 
> File "d:\Workspace\DeviceManager\dm-web\.env\lib\site-packages\django\template\base.py" in _render
>   199.         return self.nodelist.render(context)
> 
> File "d:\Workspace\DeviceManager\dm-web\.env\lib\site-packages\django\template\base.py" in render
>   994.                 bit = node.render_annotated(context)
> 
> File "d:\Workspace\DeviceManager\dm-web\.env\lib\site-packages\django\template\base.py" in render_annotated
>   961.             return self.render(context)
> 
> File "d:\Workspace\DeviceManager\dm-web\.env\lib\site-packages\django\template\loader_tags.py" in render
>   174.         return compiled_parent._render(context)
> 
> File "d:\Workspace\DeviceManager\dm-web\.env\lib\site-packages\django\template\base.py" in _render
>   199.         return self.nodelist.render(context)
> 
> File "d:\Workspace\DeviceManager\dm-web\.env\lib\site-packages\django\template\base.py" in render
>   994.                 bit = node.render_annotated(context)
> 
> File "d:\Workspace\DeviceManager\dm-web\.env\lib\site-packages\django\template\base.py" in render_annotated
>   961.             return self.render(context)
> 
> File "d:\Workspace\DeviceManager\dm-web\.env\lib\site-packages\django\template\loader_tags.py" in render
>   174.         return compiled_parent._render(context)
> 
> File "d:\Workspace\DeviceManager\dm-web\.env\lib\site-packages\django\template\base.py" in _render
>   199.         return self.nodelist.render(context)
> 
> File "d:\Workspace\DeviceManager\dm-web\.env\lib\site-packages\django\template\base.py" in render
>   994.                 bit = node.render_annotated(context)
> 
> File "d:\Workspace\DeviceManager\dm-web\.env\lib\site-packages\django\template\base.py" in render_annotated
>   961.             return self.render(context)
> 
> File "d:\Workspace\DeviceManager\dm-web\.env\lib\site-packages\django\template\loader_tags.py" in render
>   174.         return compiled_parent._render(context)
> 
> File "d:\Workspace\DeviceManager\dm-web\.env\lib\site-packages\django\template\base.py" in _render
>   199.         return self.nodelist.render(context)
> 
> File "d:\Workspace\DeviceManager\dm-web\.env\lib\site-packages\django\template\base.py" in render
>   994.                 bit = node.render_annotated(context)
> 
> File "d:\Workspace\DeviceManager\dm-web\.env\lib\site-packages\django\template\base.py" in render_annotated
>   961.             return self.render(context)
> 
> File "d:\Workspace\DeviceManager\dm-web\.env\lib\site-packages\django\template\loader_tags.py" in render
>   70.                 result = block.nodelist.render(context)
> 
> File "d:\Workspace\DeviceManager\dm-web\.env\lib\site-packages\django\template\base.py" in render
>   994.                 bit = node.render_annotated(context)
> 
> File "d:\Workspace\DeviceManager\dm-web\.env\lib\site-packages\django\template\base.py" in render_annotated
>   961.             return self.render(context)
> 
> File "d:\Workspace\DeviceManager\dm-web\.env\lib\site-packages\django\template\loader_tags.py" in render
>   70.                 result = block.nodelist.render(context)
> 
> File "d:\Workspace\DeviceManager\dm-web\.env\lib\site-packages\django\template\base.py" in render
>   994.                 bit = node.render_annotated(context)
> 
> File "d:\Workspace\DeviceManager\dm-web\.env\lib\site-packages\django\template\base.py" in render_annotated
>   961.             return self.render(context)
> 
> File "d:\Workspace\DeviceManager\dm-web\.env\lib\site-packages\django\template\defaulttags.py" in render
>   323.                 return nodelist.render(context)
> 
> File "d:\Workspace\DeviceManager\dm-web\.env\lib\site-packages\django\template\base.py" in render
>   994.                 bit = node.render_annotated(context)
> 
> File "d:\Workspace\DeviceManager\dm-web\.env\lib\site-packages\django\template\base.py" in render_annotated
>   961.             return self.render(context)
> 
> File "d:\Workspace\DeviceManager\dm-web\.env\lib\site-packages\django\template\loader_tags.py" in render
>   70.                 result = block.nodelist.render(context)
> 
> File "d:\Workspace\DeviceManager\dm-web\.env\lib\site-packages\django\template\base.py" in render
>   994.                 bit = node.render_annotated(context)
> 
> File "d:\Workspace\DeviceManager\dm-web\.env\lib\site-packages\django\template\base.py" in render_annotated
>   961.             return self.render(context)
> 
> File "d:\Workspace\DeviceManager\dm-web\.env\lib\site-packages\jet\templatetags\jet_tags.py" in render
>   64.         t = loader.get_template('admin/breadcrumbs.html')
> 
> File "d:\Workspace\DeviceManager\dm-web\.env\lib\site-packages\django\template\loader.py" in get_template
>   25.     raise TemplateDoesNotExist(template_name, chain=chain)
> 
> Exception Type: TemplateDoesNotExist at /admin/manager/devices/2/
> Exception Value: admin/breadcrumbs.html
>  

As you can see, the template "admin/breadcrumbs.html" is loaded from FormatBreadcrumbsNode class, which is instanced in format_breadcrumbs.

I checked Django 1.9.7 and Django JET 0.1.4 templates looking for it. I found admin/breadcrumbs.html in JET 0.1.4. In JET 0.9.0 this template just disappeared (and it isn't in Django 1.10), turning the tag format_breadcrumbs unusable.

Please, can you check it?

PS: I just tried to copy the old template in my app's template directory and it just worked.

**Comment by f1nality** [comment]
Hello @imdario !

0.9.0 is a major update which tries to maximally decrease number of template overrides and stick to django layout. So now it doesn't modify breadcrumbs with format_breadcrumbs tag. Btw I have forgotten to delete it completely.

In your templates\manager\view_device.html file you are using format_breadcrumbs tag as far as i understood. So a correct way to resolve this issue is to remove format_breadcrumbs tag at all and make breadcrumbs block look the same way as default django.

**Comment by SalahAdDin** [comment]
@f1nality Hey man, you have to update documentation hehehehehhe

**Comment by imdario** [comment]
> In your templates\manager\view_device.html file you are using format_breadcrumbs tag as far as i understood.

As far as I checked, I don't use it directly. Tomorrow I'll fix some post-migration "quirks" so I'll check it again (and hopefully find it).

**Comment by f1nality** [comment]
@imdario have you checked for format_breadcrumbs usage? Btw 0.9.1 update doesn't include format_breadcrumbs tag.

**Comment by imdario** [comment]
Yes, I have. It was called in a template I override. I just missed it while checking previously.
