### ISSUE TITLE
Possible problem with some many to many fields

### ISSUE THREAD

**Issue by SalahAdDin** [geex-arts/django-jet#102]
I created a repository  for shipping methods in `django-oscar`, so, i make the appropriate app and put this code in the admin:

``` python
from django.contrib import admin

from oscar.core.loading import get_model

OrderAndItemCharges = get_model('shipping', 'OrderAndItemCharges')
WeightBand = get_model('shipping', 'WeightBand')
WeightBased = get_model('shipping', 'WeightBased')


class OrderChargesAdmin(admin.ModelAdmin):
    filter_horizontal = [
        'countries',
    ]

    list_display = [
        'name',
        'description',
        'price_per_order',
        'price_per_item',
        'free_shipping_threshold'
    ]


class WeightBandInline(admin.TabularInline):
    model = WeightBand


class WeightBasedAdmin(admin.ModelAdmin):
    filter_horizontal = [
        'countries',
    ]

    list_display = [
        'code',
        'name',
        'default_weight'
    ]

    inlines = [WeightBandInline]


admin.site.register(OrderAndItemCharges, OrderChargesAdmin)
admin.site.register(WeightBased, WeightBasedAdmin)
```

So, i'll test the methods and i want add shipping countries for the existing methods.
![problem](https://cloud.githubusercontent.com/assets/5034215/17793654/9308b778-656e-11e6-8c2f-3f5269687817.gif)

You can see here that change the country field isn't saved by the admin module, and add other country replace the existing country. This problem isn't present with the other fields. In Partner models there aren't problem to add users to a partner.

Other case is this:
![seleccion_218](https://cloud.githubusercontent.com/assets/5034215/17795786/ead35d3e-6580-11e6-881f-a5ba9b5ed8be.png)
If a want delete one of theme, well, all are deleted,  but, again, doesn't save the change.

![out 04d](https://cloud.githubusercontent.com/assets/5034215/17793472/233cf018-656d-11e6-9b38-a7b94cc8acc1.gif)
But, when i do this changes in the dashboard module, i haven't problem for update the methods.

Can anyone help me to explain this?

I can't see errors in the browser console, so, i don't know which problem here.

**Comment by devrijal** [comment]
Same problem, with Django default user group permission, None of them being saved, can't add user group permission, neither user or group permission, I think the exact problem indicated on m2m

**Comment by SalahAdDin** [comment]
@f1nality Big problem here.

**Comment by f1nality** [comment]
I haven't tested with ``django-oscar`` yet, but I think the problem is that ``JET`` and ``django-oscar`` are using separate ``select2`` instances. This conflict is causing this problem.

**Comment by SalahAdDin** [comment]
Which instance use `django-jet`?

**Comment by Nofcale** [comment]
I am having the same issue, but this is new. With previous versions, django-jet was stable and an awesome skin, now in the latest version has many bugs. I have created a project with only django and django-jet installed and it doesn't work.

**Comment by lucemia** [comment]
I got the same issue without `django-oscar`.

In my case, any field which defined as `filter_horizontal` (such as user's permission), will cause admin won't save the changes correctly.

**Comment by timur-orudzhov** [comment]
From django docs:

> **ModelAdmin.filter_horizontal**
By default, a ManyToManyField is displayed in the admin site with a <select multiple>. However, multiple-select boxes can be difficult to use when selecting many items. Adding a ManyToManyField to this list will instead use a nifty unobtrusive JavaScript “filter” interface that allows searching within the options. The unselected and selected options appear in two boxes side by side.

I think, it's not a bug, filter_horizontal and filter_vertical are useless when using django-jet, but it would be useful to mention about it in docs.

**Comment by timur-orudzhov** [comment]
I think, it's not a bug, filter_horizontal and filter_vertical are useless when using django-jet, but it would be useful to mention about it in docs.

**Comment by lucemia** [comment]
@timur-orudzhov the issue here is for built-in user admin, the `filter_horizontal` is the default settings.

**Comment by f1nality** [comment]
Could you check 1.0.2 version? It fixed ``filter_horizontal`` for Django 1.10

**Comment by lucemia** [comment]
I test with django 1.9.8. it works like charm

**Comment by lukaszbanasiak** [comment]
@f1nality 1.0.2 fixed issue for me. Django 1.9.6

**Comment by Ismael-VC** [comment]
Please come to the django-jet Discord server so we can organize if you like:

  *   https://discord.gg/3yr5yeH

Welcome! 😄

**Comment by SalahAdDin** [comment]
I'm happy to say, yes! It works now.
