### ISSUE TITLE
The revenue model of Django JET

### ISSUE THREAD

**Issue by Zundrium** [geex-arts/django-jet#103]
I think Django JET has the most potential of all the Django admin extensions available to date. Simply because it has the most complete responsive experience with easy integration. 

That said, I question the renevue model of Django JET mr @f1nality.
Do you want this to be the product of a one-man army?
Or do you prefer to have a community around Django JET?

I just can't see a reason why people would want to contribute to a product, where you would have to buy a license to use the product commercially. I honestly think there are other revenue models like BountySource or donations that would not eliminate the possibility to make this a community product.

**Comment by f1nality** [comment]
@Zundrium Hello and thanks for your opinion!
Of course I prefer to have a community around JET. Though I understand that with the actual revenue model community won't be as large as it could, I still think that it will be better for the project. Smaller community makes this project not so mass and more unique. Not everyone will use it and this differs it from the default Django admin interface. So if people doesn't want to have the same admin interface as most has, they can use JET. Anyway, some people still want to contribute to JET. And of course this revenue model motivates me to make this project better more. But.. I'll think about your advice. Thanks.

**Comment by SalahAdDin** [comment]
I think that you should have two persons, at least, that help you with review pr and respond issues when you haven't time.
