### ISSUE TITLE
Broken path to jquery-ui images throws some asset compilers

### ISSUE THREAD

**Issue by philipbelesky** [geex-arts/django-jet#104]
This is a similar issue to that of #58 but in a different context. In `vendor.css` there are a number of background image paths, like so:

```
.ui-widget-content {
  border: 1px solid #aaa;
  background: url("../../../jquery-ui/themes/base/images/ui-bg_flat_75_ffffff_40x100.png") 50% 50% repeat-x #fff;
  color: #222;
}
```

The actual path for that image relative to vendor should be `/jquery-ui/themes/base/images/ui-bg_flat_75_ffffff_40x100.png` from what I can tell. There are 13 instances of these bad paths in that file (covering all of the images in `/static/jet/css/jquery-ui/images/`) along with one in `_messages.scss` (that bad path is then in the compiled `base.css` for each theme ie `light-blue/base.css` but I did not touch those as I assumed they are updated before releases)

This doesn't appear to be a problem for the display — those styles seem to be superseeded by those in jquery-ui.css in every case I could find. However they do crash [whitenoise](http://whitenoise.evans.io/en/stable/) (and possibly other) static serving methods which expect to be able to rewrite css paths. I get an error like so:

```
whitenoise.storage.MissingFileError: The file 'jet/css/themes/img/icon-no.svg' could not be found with <whitenoise.storage.CompressedManifestStaticFilesStorage object at 0x7f7133a1fa90>.
remote:        The CSS file 'jet/css/themes/light-blue/base.css' references a file which could not be found:
remote:          jet/css/themes/img/icon-no.svg
remote:        Please check the URL references in this CSS file, particularly any
remote:        relative paths which might be pointing to the wrong location.
```

I will have a pull request for this up in a second which corrects the paths.

**Comment by f1nality** [comment]
Thanks for your report! I posted a message in pull request.

**Comment by f1nality** [comment]
Could you please check if issue was fixed in dev branch?
You can install dev branch by ``pip install -e git+https://github.com/geex-arts/django-jet.git@dev#egg=django-jet``

**Comment by philipbelesky** [comment]
Looks like the dev branch has fixed this, thanks! Apologies for not checking there in the first place. I will close this and my pull request as both seem redundant.
