### ISSUE TITLE
404 when attempting to reach jet dashboard

### ISSUE THREAD

**Issue by kevin-miles** [geex-arts/django-jet#108]
Possible duplicate of #62 but there was no mention how the issue was resovled there.

Django 1.10
Django-jet 0.9.1
Python 3.5

I followed installation steps exactly and my files all match what is expected. However, if I try to reach /jet or /jet/dashboard:

`The current URL, jet/dashboard/, didn't match any of these.`

even though the URL patterns are displaying

> ^jet/ ^add_bookmark/$ [name='add_bookmark']
> ^jet/ ^remove_bookmark/$ [name='remove_bookmark']
> ^jet/ ^toggle_application_pin/$ [name='toggle_application_pin']
> ^jet/ ^model_lookup/$ [name='model_lookup']
> ^jet/ ^jsi18n/$ [name='jsi18n']
> ^jet/dashboard/ ^module/(?P<pk>\d+)/$ [name='update_module']
> ^jet/dashboard/ ^update_dashboard_modules/$ [name='update_dashboard_modules']
> ^jet/dashboard/ ^add_user_dashboard_module/$ [name='add_user_dashboard_module']
> ^jet/dashboard/ ^update_dashboard_module_collapse/$ [name='update_dashboard_module_collapse']
> ^jet/dashboard/ ^remove_dashboard_module/$ [name='remove_dashboard_module']
> ^jet/dashboard/ ^load_dashboard_module/(?P<pk>\d+)/$ [name='load_dashboard_module']
> ^jet/dashboard/ ^reset_dashboard/$ [name='reset_dashboard']
> ^jet/dashboard/ ^jsi18n/$ [name='jsi18n']

**Comment by f1nality** [comment]
Hello @kevin-miles !

Why are you trying to load /jet/ or /jet/dashboard/ urls? JET replaces original Django admin (e.x. http://your-site.com/admin/). There are some additional JET's urls such as /jet/toggle_application_pin/, /jet/dashboard/add_user_dashboard_module/, etc., but you should't try to load them yourself.

**Comment by kevin-miles** [comment]
@f1nality I was assuming thats how it would work, but for some reason even after installation my admin remains the same. Any ideas why jet wouldnt replace it?

I do have custom admin templates already in place in my templates directory.
<img width="252" alt="screen shot 2016-08-24 at 1 49 50 pm" src="https://cloud.githubusercontent.com/assets/4520234/17943586/a97b5e2e-6a01-11e6-9ea7-5084f4c041ac.png">

**Comment by f1nality** [comment]
That's the reason. JET has 3 template overrides (see https://github.com/geex-arts/django-jet/tree/master/jet/templates/admin). If you override them before JET, then it won't work. At least base.html should't be overriden or should have similar content https://github.com/geex-arts/django-jet/blob/master/jet/templates/admin/base.html. I recommend to override base_site.html instead if base.html and apply your modifications using ``block`` tag.

**Comment by kevin-miles** [comment]
Perfect, I have it up and running now after I removed my admin overrides.
Thank you for your help, I appreciate it.

**Comment by adriadrop** [comment]
Think it should be added to DOCS that if you have some template overrides it wont work. Some people will first do some overrides and then install this "theme". I did it also like that :)
