### ISSUE TITLE
Calling model_admin.get_queryset with test Request breaks plugins

### ISSUE THREAD

**Issue by mwdiers** [geex-arts/django-jet#113]
In utils.py, line 183, you create a fake request object, and pass this to model_admin.get_queryset() on line 186.

However, this ignores changes made to the request object in Django middleware. In particular, some plugins, such as Django-Guardian, require the request object to pass through the site middleware.

Django-Guardian, a row-level permissions app, expects to find the user attribute. Because you are passing it a fake Request object, the "user" attribute does not exist.

I fixed the problem by changing utils.get_model_queryset, adding an additional parameter: context, and retrieving the actual Request object from the context.

I then pass the context to utils.get_model_queryset in templatetages/jet_tags.jet_sibling_object_url()

However, there still seem to be issues with how the Guardian templates are interacting with the Jet templates that I have yet to resolve. In particular, CSRF is not passed reliably into the Guardian templates, and the User menu in the upper left is garbled.

**Comment by f1nality** [comment]
@mwdiers fake request object was replaced by this PR https://github.com/geex-arts/django-jet/pull/115 and now is available in the ``dev`` branch.
Is there still a problem with Django-Guardian?

**Comment by f1nality** [comment]
@mwdiers please check if 1.0.2 version has fixed you problem
