### ISSUE TITLE
Cannot see Groups and Permissions list

### ISSUE THREAD

**Issue by vishalbanwari** [geex-arts/django-jet#114]
@f1nality 
I cannot see Groups and Permissions list while adding User/Group. It says "No Results Found."
Although I can see Groups and Permissions in Authentication and Authorization tab.

Here is the screenshot below.
![prob](https://cloud.githubusercontent.com/assets/20904707/18268096/f1296afc-743f-11e6-8a38-534bdd86a8fc.PNG)
![prob1](https://cloud.githubusercontent.com/assets/20904707/18268115/0fb1823e-7440-11e6-9eb7-51a456777837.PNG)

The options are avialable in the page source.

![prob2](https://cloud.githubusercontent.com/assets/20904707/18347055/1b6971ac-75e1-11e6-80a8-606f0b6e7919.PNG)

Python : 2.7.9
Django : 1.10

**Comment by f1nality** [comment]
Are you using any widget packages? Here is page source from the demo:

```html
<select multiple="" id="id_groups" name="groups" tabindex="-1" class="select2-hidden-accessible" aria-hidden="true">
<option value="1" selected="selected">users</option>
</select>
```

while you have data-field-name, etc. Maybe it some sort of conflict.

**Comment by vishalbanwari** [comment]
I am using the django-import_export app.
Can't seem to find the conflict.
The groups are being shown in the page source. Why won't it show in the page?

**Comment by SalahAdDin** [comment]
Could be a problem with `django-import-export` templates?

**Comment by f1nality** [comment]
@SalahAdDin I don't think so. @vishalbanwari you have some custom ``data-field-name`` and other attributes - this should be made by some 3rd party package and I think that it can conflict with JET. Could you copy-past your ``INSTALLED_APPS`` setting?

**Comment by mzolin** [comment]
I was facing the same issue. I moved from Django 1.10.1 to Django 1.9.9 and now everything works fine, as in the demo website. Maybe there's something conflicting with Django 1.10 version.

**Comment by ashansaha** [comment]
I was facing the same issue. 
How can i customize the "jet_select2_lookups"  filter.
Please Help...

**Comment by guntursp** [comment]
I was facing the same issue here. Can't see "Groups and Permissions list" (please refer to the attachment). Here are some additional information:
INSTALLED_APPS = [
    'jet.dashboard',
    'jet',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]
Django version: 1.10.1
When I switched back to django 'default' admin template - I can see it clearly (no issue).

Probably there's something conflicting?

**Comment by guntursp** [comment]
Did anyone by any chance have any feedback regarding this subject?
Thanks
-gs

**Comment by juexiaolin** [comment]
I have the same problem, cannot see Groups and Permissions list while adding User/Group
install only:
![image](https://cloud.githubusercontent.com/assets/11309314/18950948/1655a8da-8675-11e6-8d11-2f9115809226.png)

**Comment by f1nality** [comment]
You were right, it's a issue with django 1.10 filter_horizontal. Fixed in dev and will be released in 1.0.2

**Comment by m-vdb** [comment]
it doesn't seem to be fixed in `1.10.3`, are we sure this is an issue in Django code? Do we have a link to a ticket on Django system by any chance?

**Comment by m-vdb** [comment]
it looks to me like it comes from [this line](https://github.com/geex-arts/django-jet/blob/master/jet/static/jet/css/_forms.scss#L59). A select multiple looks to be styled the same way than a select input. I'm fixing in my fork and will provide a PR :)

**Comment by ArijitWeird** [comment]
I also got the same problem. Any fix?

**Comment by SalahAdDin** [comment]
@m-vdb What's about your PR?

**Comment by m-vdb** [comment]
sorry at the time I didn't do one but instead worked on my own fork. It's a while ago so I really don't remember if I even fixed the thing

**Comment by SalahAdDin** [comment]
@m-vdb, can you share us your fork?

**Comment by m-vdb** [comment]
https://github.com/m-vdb/django-jet

**Comment by SalahAdDin** [comment]
@m-vdb Which problems solve your fork?

**Comment by AadiKshatriya** [comment]
Can we convert user permissions from multi-select options to a checkbox:
Here in this link I have asked Qeustion in StackOverflow:  https://stackoverflow.com/questions/54215295/how-to-change-django-admin-group-permissions-multi-select-options-to-checkboxes
