### ISSUE TITLE
relation "dashboard_userdashboardmodule" does not exist

### ISSUE THREAD

**Issue by timur-orudzhov** [geex-arts/django-jet#116]
When I activate dashboard module, i encounter with that problem: 

> relation "dashboard_userdashboardmodule" does not exist

Have anybody faced with the same issue ?

**Comment by f1nality** [comment]
@timur-orudzhov could you post the whole error? Looks like there are problem with your DB state. Have you applied migrations and have they run successfully?

**Comment by timur-orudzhov** [comment]
@f1nality Probably i faced with that issue, because previously i have installed django-admin-tools, that also have dashboard app and so jet.dashboard's migrations didn't apply.
