### ISSUE TITLE
draggable=False not working.

### ISSUE THREAD

**Issue by a1Gupta** [geex-arts/django-jet#117]
jet/dashboard/dashboard.py
```
class DefaultIndexDashboard(Dashboard):
    columns = 3

    def init_with_context(self, context):
        self.available_children.append(modules.LinkList)
        self.available_children.append(modules.Feed)

        site_name = get_admin_site_name(context)
        # append a link list module for "quick links"
        self.children.append(modules.LinkList(
            _('Quick links'),
            layout='inline',
            draggable=False,
            deletable=False,
            collapsible=False,
            children=[
                [_('Return to site'), '/'],
                [_('Change password'),
                 reverse('%s:password_change' % site_name)],
                [_('Log out'), reverse('%s:logout' % site_name)],
            ],
            column=0,
            order=0
     ))
```

Here even though the LinkList module is used with draggable=False,deletable=False, collapsible=False, but still the module is draggable, deletable and collapsible in admin.

I found that these settings are missing in settings_dict() and load_settings() in LinkList module. After adding these settings, collapsible and deletable are working fine but module is draggable even when draggable is False.

@f1nality Can you check this issue ? How can I make the modules static ?

**Comment by f1nality** [comment]
Actually ``draggable=False`` is not implemented. I'll fix it.
