### ISSUE TITLE
request.user not exist on admin view

### ISSUE THREAD

**Issue by zodman** [geex-arts/django-jet#120]
I using django-guardian + django-jet  and send Exception because request object dont have context request.user

https://github.com/geex-arts/django-jet/blob/master/jet/utils.py#L183

i think use the test clients code on the upstream code it's not usefull i think the PR #115 can solve it.

**Comment by zodman** [comment]
i found the reason

https://docs.djangoproject.com/en/1.10/topics/testing/advanced/#the-request-factory

RequestFactory

It does not support middleware. Session and authentication attributes must be supplied by the test itself if required for the view to function properly.

**Comment by f1nality** [comment]
fake request object was replaced by this PR #115 and now is available in the dev branch.
Is there still a problem with Django-Guardian? 
You can install dev branch by pip install -e git+https://github.com/geex-arts/django-jet.git@dev#egg=django-jet

**Comment by zodman** [comment]
fixed and tested!
