### ISSUE TITLE
Bredcrumbs on admin site without dashboard showing russian word instead of index path

### ISSUE THREAD

**Issue by hermanocabral** [geex-arts/django-jet#127]
Howdy,

When using DJ without a dashboard, the breadcrumbs on the admin index page show a russian word (I think it says beginning but my russian sucks) instead of "Home" or "Index":

![image](https://cloud.githubusercontent.com/assets/1000585/18930242/486c4a08-8595-11e6-9b22-4b7666138b71.png)

Seems like a side-effect of 81f31d08bc8a87542a54ae5322dcc3789aaa5330. Customizing the base template to comment out the ```{% block breadcrumbs %}``` block seems to do the trick if you're not using a dashboard.

**Comment by SalahAdDin** [comment]
Crazy!

**Comment by f1nality** [comment]
@hermanocabral thanks for report!
Fixed in master branch and will be released in 1.0.2
