### ISSUE TITLE
some issues

### ISSUE THREAD

**Issue by leench** [geex-arts/django-jet#13]
Django to 1.8 or later:
> /usr/local/lib/python2.7/dist-packages/django/utils/translation/__init__.py:146: RemovedInDjango19Warning: The use of the language code 'zh-cn' is deprecated. Please use the 'zh-hans' translation instead.

Require some jquery i18n files.

=====

ManytoManyField, if set 'filter_horizontal', it's not working. I'm not sure if it is my problem.

**Comment by f1nality** [comment]
1. zh-hans is the same as zh-cn, so I should just copy zh-cn to zh-hans. Am I right?
2. cannot confirm that, filter_horizontal is working with ManyToMany fields for me (Django 1.8.4)

**Comment by leench** [comment]
1. yes
2. I'll try again later.

**Comment by f1nality** [comment]
1. Fix in dev branch, will be released with 0.1.2 version

**Comment by leench** [comment]
2. It like ame i18n problem. Required 'jet/vendor/jquery-ui-timepicker/i18n/jquery.ui.timepicker-zh-HANS.js' file. I copy a other file as jquery.ui.timepicker-zh-HANS.js, it's works.

**Comment by leench** [comment]
ManytoManyField maybe is my network problem, thanks

**Comment by SalahAdDin** [comment]
Reopen this, this problem it's present until now:

![seleccion_150](https://cloud.githubusercontent.com/assets/5034215/17501735/6bcb0c3e-5da7-11e6-9cc2-84cc8fb9fa0a.png)

I test this  little code:
```python
class PartnerAdmin(admin.ModelAdmin):
    filter_horizontal = ('users', )
```

And, you can see the result in the previous photo.
