### ISSUE TITLE
Ajax lookups on admin change_list filters not working

### ISSUE THREAD

**Issue by dnmellen** [geex-arts/django-jet#14]
Hi, I don't know if it is possible, but when I try to something like:

    class YourModelAdmin(admin.ModelAdmin):
        list_filter = ['a_foreignkey_field']

When I render the change list all the data is loaded in client instead of make the proper lookups through Ajax as it does from a field represented in a change form.

Am I doing something wrong?

Thanks in advance!

**Comment by f1nality** [comment]
Hello!

Thanks to your report, I have found reason why change form ajax fields choices were being rendered on page load. This fix is already in the dev branch and will be included in 0.1.2.

Regarding ajax in filters.. filters are rendered not the same way as change form fields. Maybe the only possible solution will be to use custom filter for ajax look ups (will be included in django jet). I will see how can this be done.

**Comment by dnmellen** [comment]
Hi!

I tried your dev branch and your fix works but I needed to change a little of code to get it running also with plain ModelForms (https://github.com/geex-arts/django-jet/pull/16)

I'll research a little about the custom filters, we really need that feature.

Thanks!

**Comment by f1nality** [comment]
I've managed to achieve want you want with custom filters, I think it should be included in jet. I will format it a bit and push soon.

**Comment by f1nality** [comment]
Available in dev. To use (autocomplete_search_fields should also be set):

    from jet.filters import RelatedFieldAjaxListFilter

    class PersonAdmin(admin.ModelAdmin):
        list_filter = (
            ...
            ('address', RelatedFieldAjaxListFilter),
        )

**Comment by dnmellen** [comment]
Hi! It is awesome that you are implementing this. The search lookups are working fine, but it seems the filters are not applying when you select something.

It seems a parameter is missing, something related to data-url parameter on each choice. Maybe it is not actually filtering because of that.

**Comment by f1nality** [comment]
Have you tried clear your browser cache (refresh for me was enough)? Looks like old cached js is loaded.

**Comment by dnmellen** [comment]
Nice! You were right, it is a problem with the browser's cache.

That is really cool. I think we are close to integrate this project into production.

**Comment by f1nality** [comment]
Great, please let me know if there are any other integrating issues.
