### ISSUE TITLE
Possible DjangoCMS Issue

### ISSUE THREAD

**Issue by bculpepper** [geex-arts/django-jet#146]
I am trying to add Jet to my DjangoCMS site. Everything in the admin works fine and as expected. The issue I am having, however, is when editing a plugin. When trying to edit the content of a plugin on a page a get:

NoReverseMatch at /en/admin/cms/page/edit-plugin/2/
Reverse for 'djangocms_text_ckeditor_text_changelist' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []

Now, this error is because I clicked edit on a ckeditor plugin but I get the same NoReverseMatch for any plugin type I try to edit. For example:

NoReverseMatch at /en/admin/cms/page/edit-plugin/3/
Reverse for 'cmsplugin_filer_teaser_filerteaser_changelist' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []

Is Jet compatible with DjangoCMS? Am I missing something? Please let me know if there is any other information I can provide.

Thanks!

Brandon Culpepper

**Comment by f1nality** [comment]
@bculpepper Hello!

I haven't been using DjangoCMS for any projects, only tried to enable Jet with DjangoCMS and look for noticeable problems. So haven't seen any problems yet.

How can I reproduce your problem? Should I add some plugin? Now I have clean djangocms-installer made installation with ``jet`` added instead of ``djangocms_admin_style`` application.

**Comment by bculpepper** [comment]
@f1nality Thank you for getting back with me. I am seeing this issue once I add a plugin (any plugin) to a page and try to edit the content in the plugin. So, try to add the Text plugin to a page. Add your content and hit save. Once you save you are taken to the "Structure" layout. Click the Pencil icon to edit the content and you should see the error I mentioned above.

I will say that I am running into this on an existing DjangoCMS site that was not created using the DjangoCMS installer. If you have no issues then I will give it a go on my end using the DjangoCMS installer.

Thanks!

**Comment by f1nality** [comment]
@bculpepper I managed to reproduced this issue. Will be fixed in 1.0.3

**Comment by bculpepper** [comment]
@f1nality Thank you so much for knocking this out so fast!
