### ISSUE TITLE
Return to the line impossible in fields of type textarea. (Firefox)

### ISSUE THREAD

**Issue by blueicefield** [geex-arts/django-jet#15]
There is a problem with the textarea fields, it's not possible to do a carriage return.
It seems that the problem is located at the lines 8 and 96 of the file _forms.scss.

IMPORTANT: I have this problem only with Firefox 41.0.2 (Mac).

**Comment by f1nality** [comment]
Thanks to your report! Fix is already in the dev branch and will be included in 0.1.2.
