### ISSUE TITLE
Unable to login to admin

### ISSUE THREAD

**Issue by annamalaissh** [geex-arts/django-jet#158]
TypeError at /admin/
argument of type 'ValuesListQuerySet' is not iterable

Error during template rendering in virtualenv/local/lib/python2.7/site-packages/jet/templates/admin/base.html, error at line 176

![image](https://cloud.githubusercontent.com/assets/17566660/21353837/1ff3edbe-c6c8-11e6-9b17-09e937f3ed56.png)

**Comment by annamalaissh** [comment]
the fix will be to change this in the jet_tags.py 
pinned = list(PinnedApplication.objects.filter(user=context.get('user').pk).values_list('app_label', flat=True))

**Comment by annamalaissh** [comment]
the main problem was that the i forgot to do the migration and was searching in other places because the error message was showing a different direction. so the above mentioned fix is not needed. After i did the migrations for jet, it worked very well !!!

**Comment by joej** [comment]
I just installed django-jet, did the migrations, and this error shows up.

**Comment by shameerkashif1** [comment]
I have the same error. Would you please explain, what you did at the line pinned = ....

**Comment by pazzitul** [comment]
I solved it:
1. Delete database
2. Delete files generated by makemigrations
3. Re-execute makemigrations and migrate
