### ISSUE TITLE
TabularInline not working

### ISSUE THREAD

**Issue by Ismael-VC** [geex-arts/django-jet#183]
I have the following model definitions:

```python
class RouteUbicationInline(TabularInline):
    model = RouteUbication
    extra = 2

    formfield_overrides = {
        models.CharField: {'widget': TextInput(attrs = {'size': '20'})}
    }

class RouteAdmin(admin.ImportExportModelAdmin):
    list_display  = ROUTE_FIELDS
    search_fields = ROUTE_FIELDS
    list_editable = ROUTE_FIELDS[1:]
    inlines       = [RouteUbicationInline]

    class Meta:
        model   = Route
        fields  = ROUTE_REST_FIELDS
        exclude = [ROUTE_ID_FIELD]
```

![image](https://cloud.githubusercontent.com/assets/4594825/23329152/606ed152-faf7-11e6-9d97-03c6ca93c20b.png)

![image](https://cloud.githubusercontent.com/assets/4594825/23329168/b4b861b0-faf7-11e6-8d94-ee95ff485813.png)

`TabularInline` doesn't work for me, using:  Django 1.10.5, Python 3.6.0 and django-jet 1.0.4.

**Comment by Ismael-VC** [comment]
Please ignore this, silly me didn't notice the view has tabs! 😄

**Comment by Ismael-VC** [comment]
Yet I notice the maps don't load the first time the page loads and I change to the ubications tab:

![image](https://cloud.githubusercontent.com/assets/4594825/23329581/f8f4d6b6-fb00-11e6-9d0b-44ae2f83d951.png)

Only when I reload is when I can see the map:

![image](https://cloud.githubusercontent.com/assets/4594825/23329588/159f1380-fb01-11e6-8237-2c053eb7752e.png)

Should I add a separate issue for this?

**Comment by SalahAdDin** [comment]
@Ismael-VC yes, do it!
