### ISSUE TITLE
No date is selected when clicking on today in date widget

### ISSUE THREAD

**Issue by carlosfvieira** [geex-arts/django-jet#19]
Hi, when clicking on "today", on date widget, no date is selected:

![image](https://cloud.githubusercontent.com/assets/8830610/10895144/77be8aea-81aa-11e5-9441-280e3b5bef06.png)

**Comment by f1nality** [comment]
Thank your for your report, will fix it!

**Comment by f1nality** [comment]
Fixed in 0.1.3.
