### ISSUE TITLE
ForeignKey - add new element or edit - it's possible to do this without opening new browser window?

### ISSUE THREAD

**Issue by carlosfvieira** [geex-arts/django-jet#20]
![image](https://cloud.githubusercontent.com/assets/8830610/10895299/5e84584c-81ab-11e5-8de9-edd75b9a2b6c.png)

**Comment by f1nality** [comment]
As JET is build upon django admin this problem is related to django itself, not JET. Personally I don't see any better ways of implementing this functionality. Adding/editing form may be very large.

**Comment by f1nality** [comment]
Will be replaced with nice popups in the next version.

**Comment by carlosfvieira** [comment]
Great, thanks!

**Comment by f1nality** [comment]
Released in 0.1.4
Example http://demo.jet.geex-arts.com/admin/people/person/72/
