### ISSUE TITLE
Data loss on Validation Error [Critical]

### ISSUE THREAD

**Issue by a1Gupta** [geex-arts/django-jet#202]
There a critical issue in fk/m2m autocomplete widget. On form validation error in admin, existing data gets cleared from the form. Here are the steps to reproduce the data -

1. Add data and save.

![1](https://cloud.githubusercontent.com/assets/5560733/24831899/3bebb96c-1cc1-11e7-9cc3-4bf4a9e8514c.png)

2. Now leave a required field blank and save the form.

![2](https://cloud.githubusercontent.com/assets/5560733/24831900/3c0a8a40-1cc1-11e7-8c55-77f300236687.png)
3. Validation error will be raised and fk field data get cleared.

![3](https://cloud.githubusercontent.com/assets/5560733/24831901/3c1392a2-1cc1-11e7-9adc-0d3c095a3252.png)
4. Now correct the error and save.

![4](https://cloud.githubusercontent.com/assets/5560733/24831902/3c2a7e0e-1cc1-11e7-881a-0d332dfedc36.png)
5. **Raises error because fk field got cleared. This is a critical bug.** 
![5](https://cloud.githubusercontent.com/assets/5560733/24831903/3c2c0508-1cc1-11e7-9099-4e11aece8c85.png)

@f1nality This is a serious bug and can lead to data loss. Look into it asap. Let me know if you want any other info for reproducing this case.

**Comment by SalahAdDin** [comment]
@a1Gupta Can you provide a traceback?

**Comment by a1Gupta** [comment]
@SalahAdDin You can easily reproduce the error by following above steps. I tried it on jet demo site. In my project, I didn't get any error in django/browser console. Let me know if you fail to reproduce the issue.

**Comment by SalahAdDin** [comment]
@f1nality We have a serious problem here.

**Comment by f1nality** [comment]
Fixed in dev branch

**Comment by a1Gupta** [comment]
@f1nality @SalahAdDin Thanks :)

**Comment by f1nality** [comment]
Released in 1.0.6
