### ISSUE TITLE
checkboxes does not get rendered in custom forms

### ISSUE THREAD

**Issue by carlosfvieira** [geex-arts/django-jet#21]
picking a direct example from django-jet templates, if you try to put checkbox inputs in "password_change_form.html" template, they simply does not get rendered... only the text is rendered

**Comment by f1nality** [comment]
It's necessary for checkbox to render to have associated label **right after it**.

    <input type="checkbox" id="unique_id"><label for="unique_id">check me</label>

I can also add ability to render checkboxes without labels by adding special class to checkbox input in next version.

**Comment by carlosfvieira** [comment]
Hi, thanks for your reply!

Problem with this, is that this is not the way forms (forms.ModelForm) get rendered by default.

By default we have this rendered (has an example):
```
<li><label for="id_schedule_period-2-time_slots_0"><input id="id_schedule_period-2-time_slots_0" name="schedule_period-2-time_slots" type="checkbox" value="1" /> 08:00:00 - 12:30:00</label></li>
<li><label for="id_schedule_period-2-time_slots_1"><input id="id_schedule_period-2-time_slots_1" name="schedule_period-2-time_slots" type="checkbox" value="2" /> 13:30:00 - 18:45:00</label></li>
```

and it shows like this:
![image](https://cloud.githubusercontent.com/assets/8830610/11030819/61cc1040-86c8-11e5-9e5d-bac4432d6314.png)

I think this should be supported by default when rendering django forms objects.

What will be the correct workaround to fix this, until it gets changed for next version?

**Comment by carlosfvieira** [comment]
forgot to say that i'm using 'forms.widgets.CheckboxSelectMultiple()'

**Comment by f1nality** [comment]
@carlosfvieira sorry for the delay!

Have you found a workaround? Before I fixed you can render fields manually, like:

```html
...
                        <li>
                            <label for="{{ form.field.id_for_label }}">{{ form.field.label }}</label>
                            {{ form.field }}
                        </li>
...
```

**Comment by carlosfvieira** [comment]
Hi @f1nality , yes i know. I am using a custom css for this inputs.

Thanks!

**Comment by michaelkuty** [comment]
:+1: this is critical, because we must adjust all custom forms

**Comment by SalahAdDin** [comment]
:+1: you are right man-.

**Comment by jakubjosef** [comment]
:+1:

**Comment by cznewt** [comment]
+1

**Comment by f1nality** [comment]
```
<label><input type="checkbox"> label</label>
```

cases should now be rendered in 0.1.4

**Comment by SalahAdDin** [comment]
:+1:

**Comment by paulorsbrito** [comment]
It's still happenning today. Regression? I can't find a workaround.

**Comment by SalahAdDin** [comment]
What? @f1nality
