### ISSUE TITLE
Using jet dashboard in production causing 404 for admin page

### ISSUE THREAD

**Issue by DheerendraRathor** [geex-arts/django-jet#22]
I've recently upgraded to 0.1.3. Everything is working fine except for jet dashboard. When I'm using only `jet`  then everything is working fine. But adding `jet.dashboard` is creating 404 for admin page after login (Without login, login form for admin is rendering fine). 

Here is my configuration:
**Installed Apps:**

``` python
INSTALLED_APPS = (
    'jet.dashboard',
    'jet',
    'django.contrib.admin',
```

**URLs file**

``` python
import jet.dashboard.urls
import jet.urls
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.views.static import serve

urlpatterns = [
    url(r'^jet/', include(jet.urls, namespace='jet')),
    url(r'^jet/dashboard/', include(jet.dashboard.urls, namespace='jet-dashboard')),
    url(r'^admin/', include(admin.site.urls)),
]
```

If I remove `jet.dashboard` from `INSTALLED_APPS` then everything is working fine.

**Comment by f1nality** [comment]
Which version have you used before upgrading to 0.1.3? 
Also I need to know Django version you are using.
Does downgrading to previous version solves the problem?

**Comment by DheerendraRathor** [comment]
I had 0.1.2. Previous version had some issue regarding static files in production https://github.com/geex-arts/django-jet/issues/18 
I'm currently using Django 1.8.5 and the current django jet is working as expected in development environment. I'm using gunicorn server for production.

**Comment by f1nality** [comment]
I haven't managed to reproduce this bug. Maybe you haven't reloaded your gunicorn server after upgrading jet or something similar?

**Comment by SalahAdDin** [comment]
@f1nality @DheerendraRathor  What's about this man?

**Comment by SalahAdDin** [comment]
@DheerendraRathor Do you have problem with the lastest released version?

**Comment by Ismael-VC** [comment]
Please come to the django-jet Discord server so we can organize if you like:

  *   https://discord.gg/3yr5yeH

Welcome! 😄

**Comment by SalahAdDin** [comment]
@DheerendraRathor did you solve it?

**Comment by DheerendraRathor** [comment]
Yeah, I didn't see it in last version I used, so closed it.
