### ISSUE TITLE
Responsive design for mobile interfaces

### ISSUE THREAD

**Issue by DheerendraRathor** [geex-arts/django-jet#23]
Django jet admin interface looks awesome on a PC but it looks terrible when used over a phone. Please consider making a mobile version of the same!

**Comment by f1nality** [comment]
It's a huge task, but maybe it will be implemented sometime

**Comment by SalahAdDin** [comment]
@DheerendraRathor Can you help with this work?

**Comment by ptim** [comment]
Love the look of Jet! 
Don't think I can ship anything non responsive these days, and wish I had time to contribute, tx! 
Hope you get some great sponsors :)

**Comment by SalahAdDin** [comment]
If @f1nality will create a webpack or gulp file for scss files going to easy contribute with django-jet

**Comment by DheerendraRathor** [comment]
I'll try to work on it during summers if I don't get any other engagement.

**Comment by SalahAdDin** [comment]
A good beginning will be make a gulp or webpack files for work with scss files.

**Comment by SalahAdDin** [comment]
@DheerendraRathor what's about you man?

**Comment by f1nality** [comment]
I have done with almost a complete rewrite of JET with responsive interface. Please check if there are any problems (I have tested for ios devices only yet).

Available at feature/relayout branch
Live demo http://beta.demo.jet.geex-arts.com/admin/

Changelog:
* Almost complete layout rewrite with only 3 template overrides
* Responsive layout for mobile devices
* Reorganized scripts (Browserify + gulp)
* Updated table sortable headers style
* Fixed related object popups bugs
* Added check for JS language files existence before load

**Comment by SalahAdDin** [comment]
Have you used my gulp script? :D

**Comment by SalahAdDin** [comment]
I have only two questions:

![seleccion_169](https://cloud.githubusercontent.com/assets/5034215/17636021/5323c878-60a0-11e6-8734-cb6fa6c509e3.png)
Here, where went the site title? After this login view have the Admin Title, and i think that it's a good title for a good login view!

![seleccion_171](https://cloud.githubusercontent.com/assets/5034215/17636022/532af062-60a0-11e6-9929-be9893b4996d.png)
This is a dirty line, but i don't know if a debug toolbar button bug or a djando jet bug, because in the current version this line isn't.
![seleccion_172](https://cloud.githubusercontent.com/assets/5034215/17636146/1621f52a-60a1-11e6-8eaa-787ad1802a34.png)


![seleccion_170](https://cloud.githubusercontent.com/assets/5034215/17636096/c604561e-60a0-11e6-875d-bc0e449ae488.png)
I was trying solve how put this widget and i couldn't do it. I want congratulate to you for solve it, it's a great work. Will be better get off a little space in the gray zone.

**Comment by SalahAdDin** [comment]
Oh, the `NY` bookmark redirect us to the old demo.

And here a problem:
![seleccion_173](https://cloud.githubusercontent.com/assets/5034215/17636601/cc11bc06-60a3-11e6-8bcf-186a4bb56288.png)

**Comment by f1nality** [comment]
First of all, thanks for you answer 😉 

> Have you used my gulp script? :D

Yes, I used it as basis.

> Here, where went the site title? After this login view have the Admin Title, and i think that it's a good title for a good login view!

There are some problems with this label.

- It require template overriding while I was trying to decrease number of overrided templates (only 3 now)
- Its one more label that should be translated
- Some people doesn't want to name this page "Admin site" or name it at all.

You can always get back this label by overriding login.html and adding this label with appropriate css. I think its a cleaner solution.

> This is a dirty line, but i don't know if a debug toolbar button bug or a djando jet bug, because in the current version this line isn't.

All of your 3 screenshots with user tools bug has the same reason. And I can't understand why it happens (i don't have such bug). What browser do you have?

> Will be better add a | between both sentences here

I wanted to make it this way firstly, but when width is top small it begins to make new lines before or/and after "|" sign and it looks ugly. So I though it would be better and cleaner without any separation sign/icon.

> I don't know, but, here, the latest letters are outside the screen:

Table should be horizontal scrollable if it can't be fit into screen bounds. Doesn't it scroll?

> And, why put you buttons instead tabs in small screens?

Tabs have bottom borders which look ugly when they don't fit in a single row (they don't fit on mobile devices very ofter). So I thought it would be better to design them a lil bit different.

**Comment by ptim** [comment]
Screenshots look great! thanks for your work!

When I load the demo link http://beta.demo.jet.geex-arts.com/admin/
And fill in demo|demo, 
Then I see `Forbidden (403) CSRF verification failed. Request aborted.`

**Comment by f1nality** [comment]
@ptim it should be admin|admin
Anyway sometimes you will get 403 when database sessions being reset, just try one more time - should help.

**Comment by SalahAdDin** [comment]
Ok @f1nality 

> There are some problems with this label.
> 
>     It require template overriding while I was trying to decrease number of overrided templates (only 3 now)
But, is required override these template?

>     Its one more label that should be translated
Until now, `django-jet` have a little number of tranlatable messages, one more, well, isn't problem.

>     Some people doesn't want to name this page "Admin site" or name it at all.
This is not problem, you add a block or variable for it, for example, use the tag that you use when you want put the title in html title tag. 

> All of your 3 screenshots with user tools bug has the same reason. And I can't understand why it happens (i don't have such bug). What browser do you have?
I'm using now `Firefox 48`, so, i don't know why i have these problem.

> Table should be horizontal scrollable if it can't be fit into screen bounds. Doesn't it scroll?
I think that the browser doesn't put the scroll because is two letter out, you haven't a big column table example, so, i can't test it now.

> Does It give any significant advantages? The main disadvantage I see here that no everyone knows babel syntax, i think build script should be clear for all.
Yeah, it's ok, but i'll change it to a babel sintax for personal use :D

> But django doesn't add "+" here either. Am i wrong?
Yeah, but i don't know why the plus icon doesn't render here. In the current official version i haven't these bug.

Thank you very much!

**Comment by f1nality** [comment]
> But, is required override these template?
> Until now, django-jet have a little number of tranlatable messages, one more, well, isn't problem.
> This is not problem, you add a block or variable for it, for example, use the tag that you use when you want put the title in html title tag.

It is required to add label to login.html. Or it can be passed to base.html and than moved using js, but its a dirty solution. 
You still can override login.html and add this label in your own instance.

> I'm using now Firefox 48, so, i don't know why i have these problem.

Yes, i have reproduced it in firefox. Now its fixed.

> I think that the browser doesn't put the scroll because is two letter out, you haven't a big column table example, so, i can't test it now.

Is this table not enough big?
http://beta.demo.jet.geex-arts.com/admin/people/person/

> Yeah, it's ok, but i'll change it to a babel sintax for personal use :D

Of course its up to you)

> Yeah, but i don't know why the plus icon doesn't render here. In the current official version i haven't these bug.

It does for groups, but not for permissions.
Here django and django jet screenshots:

<img width="600" alt="2016-08-14 11 59 22" src="https://cloud.githubusercontent.com/assets/1628232/17648246/c58dcbf8-6216-11e6-967e-c2f06ca8cf7a.png">

<img width="600" alt="2016-08-14 12 00 05" src="https://cloud.githubusercontent.com/assets/1628232/17648247/c58dd97c-6216-11e6-9c4f-bb0b7c096803.png">

**Comment by SalahAdDin** [comment]
>It is required to add label to login.html. Or it can be passed to base.html and than moved using js, but its a dirty solution.
You still can override login.html and add this label in your own instance.

Ok, i'll try add a good solutions, and will make a pr.

> Is this table not enough big?
http://beta.demo.jet.geex-arts.com/admin/people/person/

Ok, yes, i'll test it, but, here twoo bugs in `firefox 48`:
![seleccion_187](https://cloud.githubusercontent.com/assets/5034215/17652112/270b60a2-623a-11e6-8147-974d25042ed5.png)
First, haven horizontal scroll in small screens.

![seleccion_188](https://cloud.githubusercontent.com/assets/5034215/17652114/2cd4d2a2-623a-11e6-9bd3-5ad09d777ff8.png)
And here, after close device emulator appears a duplicate header table, i don't know why.

>It does for groups, but not for permissions.

Oh yeah, i forgot that plus buttons is for add new objects.

And, so, man, will django jet support `filter_horizontal` and `filter_vertical` ?

Thanks man!

**Comment by f1nality** [comment]
> First, haven horizontal scroll in small screens.
> I'm testing in my current project and i found that the horizontal scroll appears in the table

It looks like a firefox emulator bug. I also have it, but it works normal in chrome emulator or real devices (iOS).

> Testing the theme picker i have a rare performance: whit the first click the theme isn't load, at least no fast, so, i do a second pick and i get this screen after, with few second the theme be loaded successfully, 
> But, this performance doesn't happen with cached styles themes, they are loaded instantly. In my local project the violet theme doesn't exist, in demo exist.

I'm not sure if anything can be done here. It depends on internet speed and device performance. With good internet and pc I don't have any problems.

> And, so, man, will django jet support filter_horizontal and filter_vertical ?

Is it needed? I find classic jet's selects much more compact giving the same functionality, I think its better than django's original filter_horizontal and filter_vertical.

> Oh, in richtext models in the demo, well, there aren't:

Hmm, will check it.

> And latest news widget height have a minor bug:

Can't reproduce it. Does it happen stable or only a few times?

> And man, what's about the Spanish localization files? These was other PR i did.

I remember issue about it, but didn't see PR. Could you give a link?
I have also refactored locale files in dev branch removing duplicates and redundant localizations, so this PR should be adopted.

**Comment by SalahAdDin** [comment]
> I'm not sure if anything can be done here. It depends on internet speed and device performance. With good internet and pc I don't have any problems.

Well, the problem is that i have a `180mb` internet speed and `16GB` RAM and `Core i7 4th Generation` computer, so, the problem isn't my laptop.

> Is it needed? I find classic jet's selects much more compact giving the same functionality, I think its better than django's original filter_horizontal and filter_vertical.

But, for some reason django have this feature, and i think, in some cases, when options are very much, is easy use these filters for have a vision field more big.

> Can't reproduce it. Does it happen stable or only a few times?

Appears for me in `Firefox` and is stable.

> I have also refactored locale files in dev branch removing duplicates and redundant localizations, so this PR should be adopted.

Ok man, i'll do it.

**Comment by f1nality** [comment]
So JET's responsive layout seems stable for now. If any problem with it appears, please create a separate issue for it.

**Comment by SalahAdDin** [comment]
Ok!
