### ISSUE TITLE
Can i set permission for Linklist for each user group

### ISSUE THREAD

**Issue by kweisamx** [geex-arts/django-jet#239]
I search for all of the document, but i don't see the function like the title, can anyone tell if the function is existed? or How do I to do this function

**Comment by SalahAdDin** [comment]
@kweisamx You have to review the title options in django admin modules, see in the official documentation.

**Comment by kweisamx** [comment]
Thanks for your reponse,
but that my question is the document page 
[http://jet.readthedocs.io/en/latest/dashboard_modules.html#build-in-dashboard-modules](http://jet.readthedocs.io/en/latest/dashboard_modules.html#build-in-dashboard-modules)
I want separate the List for each group,but I don't see the function , maybe it is not exist.

**Comment by kweisamx** [comment]
That's I find another way to solve my problem

**Comment by SalahAdDin** [comment]
@kweisamx Which?

**Comment by kweisamx** [comment]
@SalahAdDin  Just tell user to make their own linklist,because the linklist is customized.
