### ISSUE TITLE
Custom menu

### ISSUE THREAD

**Issue by pacotole** [geex-arts/django-jet#27]
Is it possible to hide (completely remove) apps and/or models in menu?

**Comment by f1nality** [comment]
Hello, @pacotole,
This feature (plus custom sorting) will be added soon

**Comment by SalahAdDin** [comment]
WHen is soon? :D

**Comment by michaelkuty** [comment]
+1

**Comment by f1nality** [comment]
It's already implemented, but I have to add docs for it and some little work. I think next week.

**Comment by f1nality** [comment]
Available in 0.1.4
Docs http://jet.readthedocs.org/en/latest/config_file.html#custom-menu

**Comment by SalahAdDin** [comment]
:+1:  Will be great put custom icons.

**Comment by f1nality** [comment]
No, its here http://demo.jet.geex-arts.com/admin/
There is an optional compact mode now.
