### ISSUE TITLE
javascript_catalog() views are removed in Django 2.0

### ISSUE THREAD

**Issue by vimm0** [geex-arts/django-jet#277]
Change import see django 2.0 release [note.](https://docs.djangoproject.com/en/dev/releases/2.0/#deprecated-features-2-0) Also [Translation](https://docs.djangoproject.com/en/2.0/topics/i18n/translation/#module-django.views.i18n)

> from django.views.i18n import javascript_catalog

>  from django.views.i18n import JavaScriptCatalog

**Comment by Chunmi-Tommy3886** [comment]
Django 2.0 The javascript_catalog() and json_catalog() views are removed.

**Comment by marcosfede** [comment]
Is there any ETA on this?

**Comment by f1nality** [comment]
Fixed in 1.0.7.
