### ISSUE TITLE
InvalidClientSecretsError  (how to attach Google account and choose Google Analytics counter to start using widget

### ISSUE THREAD

**Issue by allenLew1991** [geex-arts/django-jet#279]
![selection_004](https://user-images.githubusercontent.com/3362015/34194506-f9b240d8-e593-11e7-9129-d6ed087968f8.png)

**Comment by MIKNOTAURO** [comment]
You have to create your oauth credentials in google developer console and then set JET_MODULE_GOOGLE_ANALYTICS_CLIENT_SECRETS_FILE in your settings... 
it seems that is the wrong path file according to the traceback

**Comment by zodman** [comment]
read the docs .. https://jet.readthedocs.io/en/latest/dashboard_modules.html#extra-installation

@f1nality  close the issue

**Comment by itayseer** [comment]
add `from jet.dashboard.dashboard_modules import google_analytics_views` to the top of your root `urls.py`
