### ISSUE TITLE
Custom get_app_list() with Django JET

### ISSUE THREAD

**Issue by Jromero97** [geex-arts/django-jet#294]
Hey! I'm looking for a way to show two list of apps installed in my django project SaaS, but with django-jet only shows me the apps that I registered before, so can I modify this with my custom admin site and a get_app_list() method that I wrote?

Thanks for your help!

**Comment by SalahAdDin** [comment]
It depends of `django admin`, i think it's outside of `django-jet` scope.

**Comment by Jromero97** [comment]
Well, trying to separate list of apps, with my own get_app_list() django-jet overrides my method with own and just send me original app list, without scope (if is a tenant or main domain), we had to override the JET_SIDE_MENU_ITEMS options to get this apps dinamically...

**Comment by SalahAdDin** [comment]
Oh, there is a `PR` about it.

**Comment by Jromero97** [comment]
Yeah, I saw before that PR but is not adecuate to be scalated.. So we had to did that manually..

**Comment by SalahAdDin** [comment]
Can you make a PR?

**Comment by SalahAdDin** [comment]
Don't forget make a PR.
