### ISSUE TITLE
I can't see boolean fields

### ISSUE THREAD

**Issue by Jromero97** [geex-arts/django-jet#300]
When I put boolean fields as readonly_fields, in the admin can't see them... Neither in list_display or fieldsets...

**Comment by solvire** [comment]
Have you tried that as normal (not readonly) fields? 

I do not see boolean fields showing up in the list display.

**Comment by danilke** [comment]
+1

**Comment by Jromero97** [comment]
I solve this issue including my styles.css with the following code

`input[type=checkbox] {
    display: block;
}`

This error is due in jet-css they have `display: none;` in this property.

**Comment by SalahAdDin** [comment]
@Jromero97 can you do a pr?

**Comment by kobymeir** [comment]
I added to my code: `/static/admin/css/forms.css`

This styling:
```css
input[type=checkbox] { display: inline-block; }
```
`inline-block` is the better display type

**Comment by SalahAdDin** [comment]
@kobymeir Can you create a new PR?

**Comment by Vadorequest** [comment]
I figured out it depends on the selected theme, some default themes don't work properly

**Comment by ryanovas** [comment]
Are we talking about the little checkmark images or the checkbox itself? I was having this issue as well and had to change line 268 of _content.scss. For some reason the images have display: none put on them... Is there a particular reason this is even there? I'm not sure this issue should be closed

Specifically I did this:

```
img[src$="admin/img/icon-yes.gif"], img[src$="admin/img/icon-yes.svg"],
img[src$="admin/img/icon-no.gif"], img[src$="admin/img/icon-no.svg"],
img[src$="admin/img/icon-unknown.gif"], img[src$="admin/img/icon-unknown.svg"] {                                                                                                                                 
    // display: none;   <--- this guy right here needs to be deleted or commented out
 
   + span {
       font-weight: bold;
       color: $success-text-color;
   }
}
```

**Comment by SalahAdDin** [comment]
all pr are welcomed.

**Comment by dubitoergo** [comment]
@ryanovas This fixes the issue for me but isn't it time this is merged by someone...

**Comment by hell-io** [comment]
The issue can be solved in a different way - by overriding colors in _variables.scss for a theme. 

The colors for jet icons are defined by `$warning-text-color` and `$success-text-color` variables. Some themes like _light-violet_ have "#fff" set. You can take the values from the default theme:
```
$warning-text-color: #d49d9d !default;
$success-text-color: #82b982 !default;
```

This solution is perfectly suitable for a custom theme (I faced the trouble cause jet docs points to the light-violet theme as an example for creating your own).

**Comment by SalahAdDin** [comment]
Could you make a PR?
