### ISSUE TITLE
Django 2 autocomplete_fields

### ISSUE THREAD

**Issue by cyberbudy** [geex-arts/django-jet#319]
Django 2 added a new feature - `autocomplete_fields` but it's not displayed properly in the jet admin.

![default](https://user-images.githubusercontent.com/10235359/38600540-2df3c4f8-3d6d-11e8-99ae-98c76ce02a79.png)

**Comment by gotounix** [comment]
Also conflict with django-autocomplete-light.

**Comment by SalahAdDin** [comment]
and with `django-smart-selects`.

**Comment by anufry** [comment]
Not Fixed yet

**Comment by cyberbudy** [comment]
Probable won't be. They are working on the new jet, nothing new for a this one

**Comment by mohamedAbdElhameed** [comment]
the default behavior for django-jet with foreign key and many to many fields is equal to django admin with autocomplete_fields 
just remove autocomplete_fields and it will work well

**Comment by Alex6082** [comment]
Use - https://jet.readthedocs.io/en/latest/autocomplete.html
But it is case sensitive
