### ISSUE TITLE
Preserve currently selected tab after click on"save and continue editing"

### ISSUE THREAD

**Issue by pokidovea** [geex-arts/django-jet#32]
Now it resets to "General" tab. It is not very convenient. If it is not so difficult, keep currently selected tab open after saving. Thanks.

**Comment by f1nality** [comment]
I'll look for the way to implement it

**Comment by SalahAdDin** [comment]
@pokidovea How did you do the tabs?

**Comment by pokidovea** [comment]
@SalahAdDin When we add inlines to ModelAdmin, we have a tab for each inline model.

**Comment by SalahAdDin** [comment]
But, is it automatic?
This admin template it's awesome!

**Comment by pokidovea** [comment]
Yes, django-jet automatically adds tabs for inlines.

**Comment by SalahAdDin** [comment]
Very awesome.
So, what's news feature you want develop? i want help with this package :D

**Comment by f1nality** [comment]
jet also adds tabs for admin fieldsets
https://docs.djangoproject.com/en/1.9/ref/contrib/admin/#django.contrib.admin.ModelAdmin.fieldsets

**Comment by SalahAdDin** [comment]
@f1nality What's about this man?

**Comment by f1nality** [comment]
Implemented in 0.1.5

**Comment by ilubnon** [comment]
@pokidovea What component are you using for the image crop / thumbnail?
