### ISSUE TITLE
CheckboxInput in a MultiValueField  doesn't appear in the admin page 

### ISSUE THREAD

**Issue by AmrAnwar** [geex-arts/django-jet#332]
after only adding the **Django-Jet** to my project I found that, CheckboxInput in a MultiValueField  doesn't appear in the admin page although it was working well in the normal admin page.

---- 

### the MultiValueField field code 
```python 

class MultiWidget(forms.MultiWidget):
    def __init__(self, attrs=None):
        widgets = [
            forms.CheckboxInput(),
            forms.TextInput()
        ]
        super(MultiWidget, self).__init__(widgets, attrs)
    
   def decompress(self, value):
        if value:
            return value
        return [None, None]

class MultiField(forms.MultiValueField):
    widget = MultiWidget

    def __init__(self, *args, **kwargs):

        fields = (
            forms.BooleanField(),
            forms.CharField(),
        )
        super(MultiField, self).__init__(fields=fields, *args, **kwargs)
```
## the result in the jet admin page looks like. 

![image](https://user-images.githubusercontent.com/25433336/40934823-b9124c2a-683e-11e8-8943-0dab55111821.png)

- even if the **HTML tag** was added but I can't see the Checkbox field 
- it seems also that the problem with any **boolean field** and if I changed it to **Charfield** it works well and the 2 fields appear in the screen

**Comment by SalahAdDin** [comment]
Did you see in the issues? I think there are one similar to yours.

**Comment by AmrAnwar** [comment]
@SalahAdDin  yes you are right, you can close it

**Comment by SalahAdDin** [comment]
@AmrAnwar, i cannot, only you or repo owner can XD
