### ISSUE TITLE
Error CSS Detect

### ISSUE THREAD

**Issue by MacKey-255** [geex-arts/django-jet#335]
Hello, I have seen several errors in the CSS and I am going to send you the arrangements that I made so that everything was working. SAlu2s
[Django-jet.zip](https://github.com/geex-arts/django-jet/files/2078230/Django-jet.zip)

**Comment by zodman** [comment]
make a PR plz!

**Comment by SalahAdDin** [comment]
@MacKey-255 Don't forget modify `sass` files.
