### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by SalahAdDin** [geex-arts/django-jet#35]
Hi man, one of problem that have django-suit is that isn't locale.

Have you a locale project in Transifex? I can help you with Spanish and Turkish translation. Thanks.

**Comment by f1nality** [comment]
Transifex is not free, is it needed? You can add your translation to locale folder (*.po files):
https://github.com/geex-arts/django-jet/tree/master/jet/locale
and make a pull request after it.

I'm not a Spanish or a Turkish speaker, so it will be great if you can help with these translations.

**Comment by belugame** [comment]
I'm trying to get the jet strings into my django.po, I have my virtual env symlinked, so I run:

    ./manage.py makemessages -a -s -l de 

But it does not collect any of jet's strings. Would you know why @f1nality ?

**Comment by SalahAdDin** [comment]
@belugame I think that @f1nality should make the locale files: es and de, and we can translate it and push here :D :+1:

**Comment by f1nality** [comment]
@belugame 
You should run this command inside jet directory

@SalahAdDin 
It's not good to store totally unlocalized files in repository.

Here how you can make localization files yourself:
go to jet directory
``cd jet``
make messages
``python ../manage.py makemessages -l es``
make messages from js files
``python ../manage.py makemessages -l es -d djangojs``
after making localization (notice that there are also messages that are already translated in Django, so you don't have to translate them one more time, I have skipped them in ru translation https://github.com/geex-arts/django-jet/blob/master/jet/locale/ru/LC_MESSAGES/django.po)
``python ../manage.py compilemessages``
make a pull request

**Comment by SalahAdDin** [comment]
Ok man, i'll do these and i upload the translation.
Oh, i think that this project was finished.

**Comment by f1nality** [comment]
Thanks, that would be great!

**Comment by SalahAdDin** [comment]
Man, you have unnecessary translation strings, for example:
```po
#: dashboard/dashboard_modules/yandex_metrika.py:143
#: dashboard/templates/jet.dashboard/modules/yandex_metrika_period_visitors.html:15
msgid "Visitors"
msgstr "Visitantes"

#: dashboard/dashboard_modules/yandex_metrika.py:144
#: dashboard/templates/jet.dashboard/modules/yandex_metrika_period_visitors.html:16
msgid "Visits"
msgstr "Visitas"

#: dashboard/dashboard_modules/yandex_metrika.py:264
msgid "visitors"
msgstr "visitantes"

#: dashboard/dashboard_modules/yandex_metrika.py:265
msgid "visits"
msgstr "visitas"
```

**Comment by Bashar** [comment]
i've added Arabic translation few minutes back https://github.com/geex-arts/django-jet/pull/178 :)

**Comment by SalahAdDin** [comment]
@Bashar :+1:

**Comment by Bashar** [comment]
@f1nality Transifex is free for opensource projects

**Comment by Ismael-VC** [comment]
Please come to the django-jet Discord server so we can organize if you like:

  *   https://discord.gg/3yr5yeH

Welcome! 😄
