### ISSUE TITLE
Google analytics API request failed

### ISSUE THREAD

**Issue by nikolas310** [geex-arts/django-jet#351]
Successfully setup django-jet and everything working. But after few hours google analytics data is not showing. And displaying API request failed.
Using django 2.0(django 2.1 has compatibility issue) with latest django-jet.

**Comment by nikolas310** [comment]
Dont know, why dev is not merging security fixes quickly.
those who are using django 2.1.1 or below
use
pip install git+https://github.com/nikolas310/django-jet.git
**bug fixes:**
-> google analytics api request
-> __init__() missing 1 required positional argument: 'sortable_by' 
-> Fix render() got an unexpected keyword argument 'renderer' on django\forms\boundfield.py in as_widget, line 93

**Comment by edmenendez** [comment]
I believe the original project is dead. Is there any interesting in forking and making a django-newjet project?
