### ISSUE TITLE
Django 2.1 Fix render() got an unexpected keyword argument 'renderer'

### ISSUE THREAD

**Issue by nikolas310** [geex-arts/django-jet#352]
On `google_analytics.py` 145 no line:
Please change 

`def render(self, name, value, attrs=None):`

to

`def render(self, name, value, attrs=None, renderer=None):`

**Comment by SalahAdDin** [comment]
@nikolas310 you did a new pull request, isn't it?

**Comment by nikolas310** [comment]
Yes bro.

**Comment by Karikari** [comment]
You just have to upgrade some of your packages
I was having this problem when i upgraded to django-2.1.7 but I also upgraded some of my packages 
like django-smuggler form 0.9.0 to 0.9.1 and my issue was resolved.

**Comment by SRICKKY** [comment]
I dont have any custom render method, still I'm getting this error!
