### ISSUE TITLE
Jet template breaking in application running with apache and wsgi

### ISSUE THREAD

**Issue by MarcosAugustoOliveiraSilva** [geex-arts/django-jet#365]
Python Version: Python3
Django-jet Version: django-jet==1.0.7
Django Version: Django==2.1.1
uWsgi Versio: uWSGI==2.0.17.1

My complete requirements.txt
![image](https://user-images.githubusercontent.com/26351465/46711555-30d53180-cc23-11e8-8479-f6d923968ccc.png)

My virtualhost config
![image](https://user-images.githubusercontent.com/26351465/46711328-40a04600-cc22-11e8-80a5-2f1838145aa0.png)

My settings config
![image](https://user-images.githubusercontent.com/26351465/46711370-7ba27980-cc22-11e8-992c-e47702ab7076.png)

incorrect template image
![image](https://user-images.githubusercontent.com/26351465/46711428-aab8eb00-cc22-11e8-8557-d6ef30f92060.png)

OBS: All files load successfull, but the template breaks
OBS2: None error in apache log

**Comment by josefkorbel** [comment]
Looks like some remainings from default django admin.

Delete everything in your static folder and re-run `python manage.py collectstatic`

Also yourbrowser might be caching css, so try to reload with `CTRL+R` or `CTRL+F5`

**Comment by MarcosAugustoOliveiraSilva** [comment]
This work to me, thanks @josefkorbel

**Comment by vanyakosmos** [comment]
In firefox `CTRL+R` is just reload. To remove cache use `CTRL/CMD+SHIFT+R`
