### ISSUE TITLE
Problem login admin page on iphone

### ISSUE THREAD

**Issue by mohammad-chavoshipor** [geex-arts/django-jet#381]
Hello
Thanks for the package
Unfortunately, we're having trouble signing in with an Apple phone, and the user can not and typing a lock character.
Also in the template view in the browser, the template is also displayed in the problem display and the page scrolls and does not have a normal display that is attached.
Thankful
![image](https://user-images.githubusercontent.com/12573801/50385402-53d39580-06ea-11e9-94d9-5b29e72d659d.png)

**Comment by Chipop** [comment]
I had the same problem on pc, clearing the cache resolved it
