### ISSUE TITLE
Sass styles don't change in Browser

### ISSUE THREAD

**Issue by SalahAdDin** [geex-arts/django-jet#39]
Hi man, i'm trying to customize and complet your styles but i have a problem:
I do changes in sass files but in the browser nothing change, i refresh the browser, nothing, i try find css files but i can't find it. 

I don't know what do.

In addition, i want to do violet theme, orange theme, yellow theme, brown theme, and change the color for the other temes, but, again, if the browser doesn't take the new styles, how can i test the styles?

**Comment by f1nality** [comment]
Hello!

You have to compile scss files yourself. Each theme (e.x. https://github.com/geex-arts/django-jet/tree/master/jet/static/jet/css/themes/light-violet) contains base.scss file which should be compiled to base.css in the same folder.

**Comment by SalahAdDin** [comment]
It's ok but what's about non theme styles?

**Comment by f1nality** [comment]
What do you mean by saying "non theme"? There are only themes. Default on is located here:
https://github.com/geex-arts/django-jet/tree/master/jet/static/jet/css/themes/default

All other .scss files are included in base.scss files. So if change any .scss files, you have to recompile base.scss for changes to take effect.

**Comment by SalahAdDin** [comment]
None theme: Top.sass content.sass side_bar.sass.

These!

**Comment by f1nality** [comment]
They are not non theme. 
It's base styles for all themes, so they are included in base.scss of every theme too.

**Comment by SalahAdDin** [comment]
Ah, then, i have compilar all themes for have these modifications?

**Comment by f1nality** [comment]
Yes, because all themes use common base style. I'm using file watchers that automatically recompiles *.scss on file change for this.

**Comment by SalahAdDin** [comment]
Which file watchers? I have web pack and gulp.

**Comment by SalahAdDin** [comment]
Which file watcher man?
Now i'm working with bronw theme.
I think that branding style was default because branding style demo it's properly for all django-jet themes.

**Comment by f1nality** [comment]
I'm using PyCharm file watchers for scss.

**Comment by SalahAdDin** [comment]
I don't know ho do use it

**Comment by SalahAdDin** [comment]
Solvet using libsass, node-sass and gulp.

**Comment by HawiCaesar** [comment]
@f1nality , I have followed the instruction on the config file doc. I have implemented the file watchers for scss on pycharm but the browser still does not show the default colors I specify...What could I not have done?
