### ISSUE TITLE
ForeignKey not working in django-jet

### ISSUE THREAD

**Issue by BobbyBabazadeh** [geex-arts/django-jet#417]
Hi, 

I'm struggling with foreign-key in django-jet admin panel for couple month.
When I enable django-jet admin dashboard, fields with foreign-key shows no result found, But when I switch to django native admin interface, It will works like a charm. 
Look at the picture for more detail. This problem is a pain in my ass.
![django-jet problem](https://i.imgur.com/dmUJOSo.png "django-jet problem")

**Comment by djtsov** [comment]
@bobycloud I faced with the same problem (empty foreign field) when I use default model manager different from "objects". Did you manage to solve that problem?

**Comment by BobbyBabazadeh** [comment]
@djtsov Hi, Because of this problem I decided not to use django-jet in my project.

**Comment by himanshubarmn10** [comment]
Did anybody get any solution for it ?
