### ISSUE TITLE
TemplateSyntaxError at /admin/

### ISSUE THREAD

**Issue by xettrisomeman** [geex-arts/django-jet#434]
Error: 'admin_static' is not a registered tag library. Must be one of: admin_list admin_modify admin_urls cache i18n jet_dashboard_tags jet_tags l10n log static "

 {% extends "admin/base_site.html" %}

{% load i18n admin_static jet_dashboard_tags static %} ->admin static

This error occurred after i have finished read.me and loaded localhost/admin

**Comment by Ishma59** [comment]
Hi, were you able to solve the issue? I'm also having the same issue

**Comment by Ishma59** [comment]
found the solution! `pip uninstall django-jet` and then `pip install django-3-jet` if you are using django3

**Comment by BrainiacRawkib** [comment]
🚀 really worked.
