### ISSUE TITLE
Empty sidebar with custom admin site on Python 3

### ISSUE THREAD

**Issue by belugame** [geex-arts/django-jet#44]
I have defined a simple custom admin site:

	class CustomAdminSite(AdminSite):
		site_header = settings.SITE_TITLE
		site_title = settings.SITE_TITLE
		site_url = settings.SITE_URL
		index_title = "{} Administration".format(settings.SITE_TITLE)

After that the sidebar of my admin no longer showed any apps/models, while they remained in the main part on the right hand side:

![af770e40-c795-11e5-91ac-505919006d0c](https://cloud.githubusercontent.com/assets/16137830/12729092/4e421296-c925-11e5-8e1d-291e39eb9bf3.png)

I assume it is due to the changes of how a method is referencing it's class in Python 2 vs 3.
I found a solution that works for me in Python 3 but do not have the time to implement it cleanly and test it at the moment:  

https://github.com/belugame/django-jet/commit/9237d96ade64d534e090e47a18107a26d587bd14

**Comment by f1nality** [comment]
Fixed in 1.0.0
