### ISSUE TITLE
Duplicated DateTime display including the "old" Django Icon

### ISSUE THREAD

**Issue by eltismerino** [geex-arts/django-jet#46]
Using the current pypi version via pip and Django 1.8.8:

http://s27.postimg.org/livdokxgj/jet_datetime.png

**Comment by SalahAdDin** [comment]
:+1:

**Comment by f1nality** [comment]
It looks like .css caching issue. Have you tried to clear browser cache?

**Comment by eltismerino** [comment]
Right. It was. Thanks :)
