### ISSUE TITLE
Importation error in models using Django3

### ISSUE THREAD

**Issue by raifran1** [geex-arts/django-jet#470]
### **ERROR IN DJANGO 3**
 _from django.utils.encoding import python_2_unicode_compatible
ImportError: cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding' (/home/raifran/.conda/envs/vaskipedia/lib/python3.7/site-packages/django/utils/encoding.py)_

update archive /jet/models.py and replace 
### old calling
from django.utils.encoding import python_2_unicode_compatible

### new calling
try:
`             `from django.utils.encoding import python_2_unicode_compatible 
except:
`            ` from six import python_2_unicode_compatible # from django3

**Comment by Barukimang** [comment]
Install jet compatible with Django 3: `pip install django-3-jet`

https://pypi.org/project/django-3-jet/

**Comment by raifran1** [comment]
thank
