### ISSUE TITLE
Bootstrap support

### ISSUE THREAD

**Issue by RafRaf** [geex-arts/django-jet#48]
Hi, guys. Great job. Django-jet looks very good and shiny. Do you have any plans to support Bootstrap or any other framework? This might help to achieve a few goals simultaneously. It improves jets` design to make it mobile friendly and gives ability to users to apply other themes (skins) easily.

What do you think about it?

**Comment by SalahAdDin** [comment]
Or Foundation too!
But i think that @f1nality doesn't wants put unnecessary things in the style, for this they create a own stylesheets in scss, so, better idea it's put responsive desing in his styles. And create a good compilation file or group compilation files.
:+1:

**Comment by SalahAdDin** [comment]
@f1nality Ok man, i was thinking, for example, wagtail have a custom admin and they don't use any other front end framework, they created their custom components, so, we can create a responsive grid and other for make `django-jet` responsive, or, if we don't want created it we can use a single `bootstrap` or `foundation` components for make `django-jet` responsive.

**Comment by RafRaf** [comment]
Yeah, we can use bootstrap.responsive as an independent part and easily integrate it into the `django-jet`

**Comment by SalahAdDin** [comment]
I'm trying init with this project, but i have problem with create a webpack config file for scss watchers. Can you help me?

**Comment by RafRaf** [comment]
Hey @SalahAdDin, i use gulp to build my static assets.

**Comment by SalahAdDin** [comment]
@RafRaf which gulp config are using you for compile the themes?

**Comment by RafRaf** [comment]
Go to your django-jet/jet/static/ folder and unpack the zip file which i've attached to the message.
After that run these commands:
>> cd gulp-files
>> npm install
>> ./node_modules/gulp/bin/gulp.js

It should work.

[gulp-files.zip](https://github.com/geex-arts/django-jet/files/265304/gulp-files.zip)

**Comment by SalahAdDin** [comment]
Ah ok, have you any advance for this? news styles, news components?

**Comment by RafRaf** [comment]
I started to use "bootstrap.responsive". In progress..

**Comment by SalahAdDin** [comment]
But, only responsive styles or are styles?

**Comment by RafRaf** [comment]
I'm talking about integration of bootstrap.responsive styles into the package. Inability to work on mobile devices is the main reason not to use `django-jet` in my projects.

**Comment by SalahAdDin** [comment]
Ok, we will integrate only responsive styles for the project. In addition i'm working in other admin skin if you want help us.

**Comment by RafRaf** [comment]
>  In addition i'm working in other admin skin if you want help us.
Very good

**Comment by SalahAdDin** [comment]
Ok man, if you want i can find you in gmail and tell you more about it. And can manage this skin and the other skin.

**Comment by SalahAdDin** [comment]
@RafRaf Hey man, his gulpfile compile the all css themes in each folder?

**Comment by RafRaf** [comment]
`Ok man, if you want i can find you in gmail and tell you more about it. And can manage this skin and the other skin.
@SalahAdDin`
Ok

**Comment by SalahAdDin** [comment]
Ok man, i don't know what happen with this, but, gulp doesn't transpile the scss files:
![captura de pantalla de 2016-05-22 22-13-01](https://cloud.githubusercontent.com/assets/5034215/15459401/82f7596e-206a-11e6-9404-d91e8010237e.png)
![seleccion_096](https://cloud.githubusercontent.com/assets/5034215/15459413/a08a378a-206a-11e6-92e5-3e91f6cd74a1.png)
![seleccion_097](https://cloud.githubusercontent.com/assets/5034215/15459420/adcf1640-206a-11e6-8d4b-ff67a87807e5.png)
I have the same project's structure, but, i don't know what happen with this :'(

**Comment by SalahAdDin** [comment]
Related: https://github.com/geex-arts/django-jet/issues/23

**Comment by SalahAdDin** [comment]
Guys, a question about this: https://github.com/JensAstrup/django-jetpack/issues/30

**Comment by f1nality** [comment]
I'm currently working on updated layout. It will be responsive and I'll try to decrease number of template overrides as much as it possible (only base.html in theory) because now there a lot of problems with 3rd party applications. It requires making layout from scratch so it won't be fast, till September i think. Also there will be script that will build all static (I haven't work with gulp, only so it will be grunt i think)

**Comment by SalahAdDin** [comment]
I haven't problem with any third party package, django-import-export templates work's properly yet.

But, i'd worked in django-jet by months, i create a full gulp script for compile sass files and other features, and i want to know if my work will be in this package.

[Here](https://github.com/SalahAdDin/django-jetpack) are our fork with the full work.

If you want i want be this respository mantainer, or, i don't know, i wrotte you some time ago but you never answer me.

I like so much this skin and i want work in it.

Thanks.

**Comment by f1nality** [comment]
@SalahAdDin  Yes, I haven't enough time for maintaining JET, now I can get back to updating it)
I'll check your fork. Are there reasons why you've chosen gulp instead of grunt? I've heard it should be faster, but I haven't tried it yet.

But there are packages (e.x. constance which have layout conflicts) which doesn't work properly and it's bad that new updates in django templates are ignored because of templates overriding.

Now I have to make some big updates to layout before implementing some minor changes.

**Comment by SalahAdDin** [comment]
Ok man, i'll make a big PR with other minor changes for testing and other things and i'll send you.

Gulp is less complicated that Grunt, and more faster and easier setting up.

**Comment by SalahAdDin** [comment]
@f1nality 
I wants show you my progress working with this package:
![seleccion_137](https://cloud.githubusercontent.com/assets/5034215/17282219/37e01cf0-5769-11e6-930e-b9e9e490a4a6.png)

I get on some responsive tweaks in sidebar and dashboard header, i added date/time information and site title in side bar (some like djanto-jet demo) and other minor fixes.

I take these ideas from `django-suit`:
![seleccion_138](https://cloud.githubusercontent.com/assets/5034215/17282240/798b43f0-5769-11e6-96ed-a02d07e91098.png)

What do you think?

**Comment by SalahAdDin** [comment]
@f1nality Hi man, you can see [here](https://github.com/gulpjs/gulp/issues/540) wich people use Gulp.

**Comment by f1nality** [comment]
@SalahAdDin yes, gulp is really cool. Please check issue https://github.com/geex-arts/django-jet/issues/23 for a new version of JET with updated responsive layout. It doesn't depend on bootstrap so I think this issue is not actual now.
