### ISSUE TITLE
ImportError: python_2_unicode_compatible

### ISSUE THREAD

**Issue by Samiddha99** [geex-arts/django-jet#487]
I am using **Django==3.2.**
During the time of running `python manage.py migrate jet` command, I'm getting the following error:
```
ImportError: cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding'
```
Why it's not found the module?
How to fix the problem?

**Comment by Barukimang** [comment]
Use the django3 version of Jet: `pip install django-3-jet`
