### ISSUE TITLE
modules.AppList documentation bogus/wrong

### ISSUE THREAD

**Issue by eltismerino** [geex-arts/django-jet#49]
https://github.com/geex-arts/django-jet/blob/master/jet/dashboard/modules.py#L271 states:
`Specify models which should be displayed. ``models`` is an array of string formatted as app_label.model`

This doesn't work. Only the model name itself is accepted here: https://github.com/geex-arts/django-jet/blob/master/jet/dashboard/modules.py#L296 uses context["object_name"] which does *not* include the app label.

**Comment by SalahAdDin** [comment]
So, how will you change this wrong documentation?
