### ISSUE TITLE
this project will no longer be maintained???

### ISSUE THREAD

**Issue by CARocha** [geex-arts/django-jet#510]
si la respuesta es si, porque mejor se lo pasan a jazzband https://github.com/jazzband
this project is very beautiful they should not let it die

**Comment by Barukimang** [comment]
Hej @CARocha It's not actively maintained anymore, but it has been updated for Django 4, you can find it here: https://pypi.org/project/django-4-jet/

**Comment by CARocha** [comment]
Oh, great news! thank @Barukimang ,sure i will use it soon :)
