### ISSUE TITLE
Connection refused by localhost when trying to add a foreign key in new model

### ISSUE THREAD

**Issue by webtomek** [geex-arts/django-jet#515]
I have 2 models, one has a foreign key pointing to the other model. When I press "Add item" in the first model, I can press the plus button next to the foreign key field to add another to that model, but when I click it, it says "Connection refused by localhost".

`class Currency(models.Model):
    name = models.CharField(max_length=200, null=False, blank=False)

class Item(models.Model):
    name = models.CharField(max_length=200, verbose_name="Megnevezés", blank=False)
    curr = models.ForeignKey(Currency, max_length=50, blank=False, on_delete=models.CASCADE)
`

screenshot: https://imgur.com/a/f1AFAY1

django version: 4.0.6
jet version: newest.

**Comment by dresl** [comment]
I had the same problem. Try add this to `settings.py`:
```python
X_FRAME_OPTIONS = 'SAMEORIGIN'
```

**Comment by webtomek** [comment]
Abandoned repo I guess.
