### ISSUE TITLE
Pop up content redirect to a new page

### ISSUE THREAD

**Issue by SalahAdDin** [geex-arts/django-jet#52]
Hi man, 

I think, by default, all pop up content have to open a new windows, where do anything and when you click in button, close this window. But, in Django-Jet all pop up links rediret to new url instead open a new window. Why?

![mozilla firefox_005](https://cloud.githubusercontent.com/assets/5034215/13198761/8a1f09e0-d7df-11e5-8ab4-f448c95f156a.png)

Is a register new object form and are in the same window, isn't a extern window.

**Comment by f1nality** [comment]
Hello @SalahAdDin !

In latest django jet popups should look like this

<img width="1440" alt="2016-03-05 23 39 26" src="https://cloud.githubusercontent.com/assets/1628232/13550295/ac736aa2-e32b-11e5-920f-2b4cc4cb8c5b.png">

Maybe there is some problem with static files (not run collect_static or browser cache problems)?

**Comment by SalahAdDin** [comment]
Which is the last version? I'm production, so, i don't know why i have problems with it.

**Comment by f1nality** [comment]
0.1.4 is the latest.

**Comment by dnmellen** [comment]
I can reproduce this issue with Django 1.9. It seems is related with the new way Django handles javascript overrides (see https://docs.djangoproject.com/en/1.9/ref/contrib/admin/javascript/ and https://github.com/django/django/commit/0decef337f7f00d73b380531ac22cbc843d6e806)

I know the current stable Django version is 1.8 but it is very important for many people that django-jet is Django 1.9 compatible.

Thanks!

**Comment by SalahAdDin** [comment]
:+1:

**Comment by f1nality** [comment]
0.9.0 has fixed Django 1.9 new js usage which conflicted with jet.

**Comment by wonook** [comment]
For some of those trying Django-jet on Django 3.0+, you have to set `X_FRAME_OPTIONS = 'SAMEORIGIN'` in order for the popup contents to work.
