### ISSUE TITLE
Autocomplete fails because of related_model property

### ISSUE THREAD

**Issue by dnmellen** [geex-arts/django-jet#54]
Hi, maybe is not a django-jet issue, but if I use `RelatedFieldAjaxListFilter` I get a server error because `related_model` is returning a string instead of a model instance.

I also reported this behaviour on stackoverflow because maybe is a Django issue:
http://stackoverflow.com/questions/35745607/why-djangos-related-model-property-is-returning-string-instead-of-model-instanc

A possible workaround is to directly get the related model through `field.remote_field.model`

    app_label = field.remote_field.model._meta.app_label
    model_name = field.remote_field.model._meta.object_name

I need to do this workaround for me and I can make a pull request if you think it is interesting to avoid future problems.

Thanks!

**Comment by SalahAdDin** [comment]
:+1:

**Comment by f1nality** [comment]
Merged and fixed in dev.
I have added tests for this issue to make sure it works for older Django too.
