### ISSUE TITLE
Missing/placeholder icons pose problems for static file serving

### ISSUE THREAD

**Issue by philipbelesky** [geex-arts/django-jet#58]
There are a few a couple of icons that are loaded as such:

    <img src="{% static "admin/img/icon-unknown.gif" %}" ..... />

The CSS and JS then matches that `src` path and then replaces the icon in many circumstances. However, these icons have been removed or change to be SVG files as of Django 1.9 and can throw exceptions depending in some circumstances (for me using whitenoise and with debug off).

I can probably do a pull request to fix that — in which case should I amend #45 to create a more generic "django 1.9 or above" tag and do a bunch of if/elses? Is there a more elegant solution?

**Comment by SalahAdDin** [comment]
:+1:

**Comment by f1nality** [comment]
Fixed in 0.9.0 by extending selectors.
