### ISSUE TITLE
Cannot Reach Jet, Raises 404

### ISSUE THREAD

**Issue by erayerdin** [geex-arts/django-jet#62]
I installed and correctly configured for `django-jet`. However, when I request for url `jet/` or `jet/dashboard`, it responses 404, saying:

 > The current URL, jet/, didn't match any of these.

***

#### INSTALLED_APPS

    INSTALLED_APPS = [
        # Outsource
        "jet.dashboard",
        "jet",

        # Main
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',

        # Outsource
        "rest_framework",

        # Self
        "api",
        "blog",
        "cvitae",
        "activities",
    ]

#### TEMPLATES

    TEMPLATES = [
        {
            'BACKEND': 'django.template.backends.django.DjangoTemplates',
            'DIRS': [
                os.path.join(BASE_DIR, "templates"),
                os.path.join(BASE_DIR, "templates/responses")
            ],
            'APP_DIRS': True,
            'OPTIONS': {
                'context_processors': [
                    'django.template.context_processors.debug',
                    'django.template.context_processors.request',
                    'django.contrib.auth.context_processors.auth',
                    'django.contrib.messages.context_processors.messages',
                ],
            },
        },
    ]

### urls.py

    urlpatterns = [
        url(r'^jet/', include('jet.urls', 'jet')),
        url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
        url(r'^admin/', admin.site.urls),
        url(r"^api/", include("api.urls")),
        url(r"^blog/", include("blog.urls")),
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

I migrated and run server but could not help.

***

# Environment
 - python 3.5.1
 - django 1.9.5
 - django-jet 0.1.4

**Comment by SalahAdDin** [comment]
You need install the google-python or whatever called package for make this functional, the other way, ever have problems, i tested this many times.

**Comment by JensAstrup** [comment]
Was this solved/can it be closed?

**Comment by erayerdin** [comment]
Yes, it is solved. :) I am closing it.

**Comment by kevin-miles** [comment]
@erayerdin I am experiencing this same issue. Could you possibly share what you did to resolve it?

only difference on my end is that im using django 1.10.

**Comment by Jromero97** [comment]
Could you give me the exactly name of the package? I have the same error but I don't know if that package is the solution to my problem.

**Comment by CodeSpent** [comment]
I second this. Could we get the name of the package you installed to solve this? Closed issues should include a complete solution. Is it the Google Analytics package, and if so why would that be a necessary dependency? I've tried installing that anyways just to see, and there's no difference. Please let us know what "google python package thingy" can be installed to resolve.
