### ISSUE TITLE
Foreignkey Popup Window is Not Closing After Saving

### ISSUE THREAD

**Issue by ranjithtenz** [geex-arts/django-jet#63]
Hi All,
How can we auto close the foreignkey popup window after saving the foreignkey form and also How to set foreignkey option which is been currently saved.

**Comment by clint74** [comment]
It seems to be related with this issue [https://github.com/geex-arts/django-jet/issues/52](https://github.com/geex-arts/django-jet/issues/52), no?

**Comment by SalahAdDin** [comment]
@clint74 I think so.

**Comment by f1nality** [comment]
0.9.0 has fixed Django 1.9 new js usage which conflicted with jet.
