### ISSUE TITLE
list_editable checkbox don't show

### ISSUE THREAD

**Issue by h00p** [geex-arts/django-jet#69]
list_editable field don't render in admin, 

in admin py:
`list_editable = ['slider']`

checkbox input has html code:

`<input checked="checked" id="id_form-0-slider" name="form-0-slider" type="checkbox">`

and css rule:

`input[type=checkbox] {
    display: none;
}`

**Update:**
if i hardcoded .field-slider in main.js addLabelToCheckboxes $containers then all works fine

**Comment by SalahAdDin** [comment]
man, if you want try with my dev branch if that was resolvet yet.

**Comment by SalahAdDin** [comment]
Make a PR please.

**Comment by f1nality** [comment]
Fixed in 1.0.0
