### ISSUE TITLE
All selection checkbox does not select all listed items

### ISSUE THREAD

**Issue by noodlebreak** [geex-arts/django-jet#7]
Hi,

First of all, the UI is awesome. Thank you, for open sourcing this.

Secondly, the bug:

I just wanted to delete all instances from a model. I checked the all-selection check box.
But nothing was selected.

It's is happening all over the place. In all the models.

**Comment by mightygraf** [comment]
Thanks for opinion.
This bug will be fixed in the next release.

**Comment by mightygraf** [comment]
Fixed in 0.0.7

**Comment by noodlebreak** [comment]
Awesome! Thank you!
