### ISSUE TITLE
white spaces 

### ISSUE THREAD

**Issue by BowSplinter** [geex-arts/django-jet#71]
Trying out django jet but results in white spaces in the top and in the side toolbar.
![image](https://cloud.githubusercontent.com/assets/15277589/15818561/65d98210-2bde-11e6-9f4c-a47bbb3bfbdb.png)

Using:
Django (1.8.13)
Django CMS (3.2.5)

Any idea what the issue might be? Was messing around with the cms toolbar but I tried disabling it and it still doesnt change things.

**Comment by SalahAdDin** [comment]
I don't understand you, what doing you try?

**Comment by BowSplinter** [comment]
just trying to apply django jet to my admin. as you can see there are white spaces on the sidebar and a hortizontal white space on top. Not sure if bug or compatibility issues?

**Comment by SalahAdDin** [comment]
But, it isn't normal, i haven problem that kind when installing the current version.
Did you try to override the css styles?

**Comment by BowSplinter** [comment]
I found my mistake, 'jet' needs to be above 'djangocms_admin_style' or djangocms templates will mess around with the template.

as such..

```
INSTALLED_APPS = (
    ...
    'jet',
    'djangocms_admin_style',
)
```

Thanks
