### ISSUE TITLE
List Editable in Boolean Field

### ISSUE THREAD

**Issue by JuniorLima** [geex-arts/django-jet#72]
https://twitter.com/JuniorLimaPlus/status/739804390937272320

List_Editable does not work with boolean

https://pbs.twimg.com/media/CkRQK9dWUAEjaH2.jpg:large

**Comment by h00p** [comment]
I think it's same [#69](https://github.com/geex-arts/django-jet/issues/69)

**Comment by f1nality** [comment]
Fixed in 1.0.0
