### ISSUE TITLE
Multiple problems with select2 plugins

### ISSUE THREAD

**Issue by SalahAdDin** [geex-arts/django-jet#74]
Hi, i'm working with a some complex tables in my project and i can find some problems with select inputs, i have many select input fields in my project:

![problemaconinputselects_1](https://cloud.githubusercontent.com/assets/5034215/15875100/04777a92-2ccc-11e6-8b06-e225e52c43a1.png)
As you can see, the 'fake' input select cause that they duplicate in the rendered html.
![masproblemasinputs](https://cloud.githubusercontent.com/assets/5034215/15875102/0481de38-2ccc-11e6-9606-8abdae2a663d.png)
And in this case, i don't know why, after all 'fake' input selects we can see the edition or creation buttons.
![replicanproblemas](https://cloud.githubusercontent.com/assets/5034215/15875101/047bfe32-2ccc-11e6-96ec-e49089e9e6b0.png)
Oh no, duplicate no, triplicate and anymore, each time that i come back to the chage list view, this fields over renderized in screen, duplicating, triplicanting and anymore again.
![ymasproblemas](https://cloud.githubusercontent.com/assets/5034215/15875107/04ce5e66-2ccc-11e6-9478-11d2f6a7d743.png)
And some times the input select doesn't duplicate in horizontal, no, vertical too.

And in a new issue i put other problems with it, but different kind.

**Comment by SalahAdDin** [comment]
Related: https://github.com/geex-arts/django-jet/issues/75

**Comment by Ismael-VC** [comment]
Please come to the django-jet Discord server so we can organize if you like:

  *   https://discord.gg/3yr5yeH

Welcome! 😄

**Comment by SalahAdDin** [comment]
After the final version this problems are fixed.
