### ISSUE TITLE
Perfect scroll problems

### ISSUE THREAD

**Issue by SalahAdDin** [geex-arts/django-jet#76]
Hi, as you can see some times Perfect Scroll doesn't works correctly:

![aunmasproblemas](https://cloud.githubusercontent.com/assets/5034215/15894620/6b01447a-2d4c-11e6-9c1a-36129f8232a2.png)
Some times, horizontal layout breakout and get out of the normal layout, in this case the break isn't too much, but when the tables have many columns the horizontal layout break out yer or yes. This problem, i didn't see, happens with vertical layout.

![aypordiosproblemas](https://cloud.githubusercontent.com/assets/5034215/15894619/6aff0020-2d4c-11e6-9493-1fbbfb6aa5a8.png)
Here we can see the same problem.

**Comment by f1nality** [comment]
Perfect scroll works only for sidebar. Is this problem actual for 0.9.0+ versions?

**Comment by SalahAdDin** [comment]
I'll verify this, until then, please, don't close this issue :D

**Comment by Ismael-VC** [comment]
Please come to the django-jet Discord server so we can organize if you like:

  *   https://discord.gg/3yr5yeH

Welcome! 😄

**Comment by SalahAdDin** [comment]
@f1nality Is fixed now, works perfect, but i think will be better add a gray scroll bar.
