### ISSUE TITLE
"icon-deletelink.svg" issue about Foreign Keys

### ISSUE THREAD

**Issue by metinkilicse** [geex-arts/django-jet#77]
When I want to add new record which has foreign key, delete icon next to the foreign key field gives a "not found" error because django-jet uses "icon_deletelink.gif"(earlier 1.9) rather than "icon-deletelink.svg"(1.9) on "related_widget_wrapper.html" file line 23. Add and Edit icons work well but delete icon gives a "static/admin/img/icon_deletelink.gif" not found error. When I changed that line to icon-deletelink.svg, it uses default django template's icon which is not so good. So any help would be great about that.

**Comment by SalahAdDin** [comment]
I'm thinking replace the jet icons with font-awesome icons or material-ui icons. But i don't know how is `icon_deletelink.gif` or witch animation have it.

**Comment by f1nality** [comment]
Fixed svg icons issues in 0.9.0.
