### ISSUE TITLE
<ul> element error about password warning on password change form

### ISSUE THREAD

**Issue by metinkilicse** [geex-arts/django-jet#78]
When I go to change password page, it doesn't show proper password warnings well because of <ul> tags.

Default Django theme uses  " | safe " to solve this.
In django-jet, on templates/registration/password_change_form.html line 36 and 44, you should put "**| safe**" after "**help_text**" to solve this problem.

**Comment by SalahAdDin** [comment]
Yes, other user make a pr solving this, but @f1nality doesn't merge it.
I'll merge it in my branch.

**Comment by JensAstrup** [comment]
Noticed this as well, I made the pull request #73 which fixes the issue. It's a very small change so you can easily add it into your own fork.

**Comment by f1nality** [comment]
0.9.0 doesn't override change password page, so now there won't be problems with it.
