### ISSUE TITLE
Inline form events in Django 1.9

### ISSUE THREAD

**Issue by jturmel** [geex-arts/django-jet#79]
https://docs.djangoproject.com/en/1.9/ref/contrib/admin/javascript/

**Comment by SalahAdDin** [comment]
I don't understand your issue.

**Comment by jturmel** [comment]
Jet redefines admin/js/inlines.js so it's not calling this new event that was added in Django 1.9

**Comment by SalahAdDin** [comment]
In that case we need delete this file, right?

**Comment by jturmel** [comment]
I suppose if you just did that it'd break things in Jet, otherwise they wouldn't have overridden it. I didn't dig in as I've got a deadline I'm trying to hit at the moment so I just threw in the one event line for now. A proper diff between 1.8 and 1.9 for that file to see all of what they changed would be the way to go. That may be the only change.

**Comment by SalahAdDin** [comment]
Oh man, it sounds really hard, can you help with this?

**Comment by f1nality** [comment]
Since 0.9.0 JET doesn't override inlines.js.
