### ISSUE TITLE
Licensing issues

### ISSUE THREAD

**Issue by xrmx** [geex-arts/django-jet#8]
First GPL2 permits commercial usage so this "Free for non-commercial use under the GPLv2 license." is very wrong. The "issue" with GPL2 it's that being viral it spreads to eventual derivative code. 

Second on pypi https://pypi.python.org/pypi/django-jet/ you have an old README version that links to creative commons instead of GPL 2.
~~~
License

Django JET is licensed under a The GNU General Public License, Version 2

See online version of this license here: https://creativecommons.org/licenses/by-nc-sa/4.0/
~~~

Thanks

**Comment by denis-kildishev** [comment]
Yes, it permits, but such products should also be GPLv2 - i doubt that someone would like to make commercial products open source. Making these products non open source is not free - that is what it was meant. I agree that this quote is a bit wrong. How it should sound instead?

README on pypi was an old one, now it's the same as on github.

**Comment by xrmx** [comment]
"Please note that using GPL code in your programs make them GPL too. So if you don't want to comply with that we can provide you a commercial license." or whatever makes sense for you :)

**Comment by f1nality** [comment]
Thanks for your wording, will update it soon

**Comment by f1nality** [comment]
Text updated
