### ISSUE TITLE
Is this repo active?

### ISSUE THREAD

**Issue by Zundrium** [geex-arts/django-jet#82]
Since the last commit was on 5 March 2016 on the dev branch I have the feeling this repo is no longer maintained. Are the contributors on a break or is the code frozen for now?

Would be a shame, since it's the only admin interface with good looks and uses the normal `admin.ModelAdmin` in `admin.py`.

**Comment by SalahAdDin** [comment]
I'm working in it, but i'm not collaborator, i have a fork if anyone want help me to improve this great admin.

**Comment by JensAstrup** [comment]
I've created a [new git repo](https://github.com/JensAstrup/django-jetpack) and a [pip package](https://pypi.python.org/pypi/django-jetpack/1.0.0b0). I'm moving all pull requests from this project to the new repo so that we can get them integrated. Issues will need to be moved over as well. Happy to add people in as collaborators if you're interested - would like to get more people involved so we don't have the same issue :)

**Comment by SalahAdDin** [comment]
Please, add me and fork my branch, i merged all change and add my custom changes.
@JensAstrup

**Comment by JensAstrup** [comment]
Added you as a collaborator - feel free to make a pull request with your changes (on the jet_pull_re branch). I made a clean-slate repo which makes the initial moving over a little painful, but should make things easier in the long run.

**Comment by SalahAdDin** [comment]
But my branch ins linked to this project, not the other project.

**Comment by JensAstrup** [comment]
You can still merge the changes - just make a branch on the new repo, and copy over your changed files

**Comment by SalahAdDin** [comment]
Ok, this afternoon i'll test it, for now i think that you can create an issue with all possible bugs and solutions, features and others, if you want inspire in django-suit or other, is a complete admin, but haven't this great skin.

**Comment by f1nality** [comment]
I haven't enough time for maintaining JET this spring, now I can get back to updating it.
0.9.0 major update has already been released.

I have done with almost a complete rewrite of JET with responsive interface. Please check if there are any problems (I have tested for ios devices only yet). This major release is going to be version 1.0 (first stable release) after checking if everything is ok (0.9+ versions for now).

**Comment by SalahAdDin** [comment]
@f1nality Thank you man!
