### ISSUE TITLE
ManytoMany Field wrong in Firefox.

### ISSUE THREAD

**Issue by SalahAdDin** [geex-arts/django-jet#84]
I'm seeing the user admin view and i can see that the permissions and group with default django-admin configuration for manytomany field, doesn't works.

This is the current view:
![problema_jet_con_horizontal_filter](https://cloud.githubusercontent.com/assets/5034215/16162685/8e570f04-349a-11e6-9a65-cdfd1d719398.png)

And this is an example how should be viewed:
![change_user___django_suit_asi_deberia_verse](https://cloud.githubusercontent.com/assets/5034215/16162689/9a2c1aa4-349a-11e6-82ee-80b400ce0e69.png)

Testing more deeper i found that the problem is with firefox, in google chrome i haven't these problem.
![engooglechromefuncionabien](https://cloud.githubusercontent.com/assets/5034215/16162870/b0516162-349b-11e6-85e9-9c580c49f02a.png)

How solve it?

I'll test with `filter_horizontal` and `filter_vertical` for review if works.

**Comment by SalahAdDin** [comment]
Until now, [the bug still it's present](https://github.com/geex-arts/django-jet/issues/13).

**Comment by SalahAdDin** [comment]
@f1nality Have you thought implements the `filter_horizontal` and `filter_vertical` javascript feature?

**Comment by f1nality** [comment]
I don't see real reasons for it.  I see these ``filter_horizontal`` and ``filter_vertical`` advantages compared to default select:
1. Search
2. Multiselect without non intuitive UX (ctrl+click)
3. Displaying selected items separately

Django JET selects have all these advantages, so what's the real reason for it?

**Comment by Ismael-VC** [comment]
Please come to the django-jet Discord server so we can organize if you like:

  *   https://discord.gg/3yr5yeH

Welcome! 😄

**Comment by SalahAdDin** [comment]
@f1nality After the last version this problem was solved.

**Comment by ApaDoctor** [comment]
Problem still exists in 2019.
`filter_horizontal` doesn't change anything. (Horizontal filtering doesn't appear).

(Chrome)

**Comment by denzel-beowulf** [comment]
> Problem still exists in 2019.
> `filter_horizontal` doesn't change anything. (Horizontal filtering doesn't appear).
> 
> (Chrome)

I can confirm that on Firefox too.

**Comment by petersenpeter** [comment]
Still a problem in 2021! Anybody found a fix for this?

**Comment by SalahAdDin** [comment]
> Still a problem in 2021! Anybody found a fix for this?

This package is deprecated man, sorry.

**Comment by petersenpeter** [comment]
Thanks, but still in use. :-)
