### ISSUE TITLE
Problem with `LANGUAGE_CODE` complete localization

### ISSUE THREAD

**Issue by SalahAdDin** [geex-arts/django-jet#85]
I can see this bug:
![problemas-con-localizacion-es-co](https://cloud.githubusercontent.com/assets/5034215/16162926/1df8bfe4-349c-11e6-97ea-0c27e9a43eb0.png)
Whe i put  `LANGUAGE_CODE = 'es-co'`i get these error, but if only put `LANGUAGE_CODE = 'es'`i haven't problem with it.

So, how can we solve this?
I think that will make a method that get the language code and try to search the localization file with the full language code, and if can't find it, trim the language code for get the global localization file.

**Comment by SalahAdDin** [comment]
Hey guys: Any suggestion https://github.com/JensAstrup/django-jetpack/pull/4 ?

**Comment by f1nality** [comment]
Same as https://github.com/geex-arts/django-jet/issues/92
0.9.0 checks locales files for existance and tries less specific locales if possible ("es" instead of "es-CO" if it doesn't exist).

**Comment by SalahAdDin** [comment]
@f1nality The problem is that by default we put the language code setting completly, so, if i'm in Ecuador, i put 'es-ec', or i'm méxico, 'es-mx', is normal, so, you could change these option for get the first part of language code, or, by default, the current language in cache.

**Comment by f1nality** [comment]
So isn't this problem fixed?
If you specify e.x. "es-ec" it will search for "es-ec" localization files and include them, if there are no such - it will look for "es", if "es" doesn't exists also - JS will use default "en" localization". Looks like a bulletproof solution.

**Comment by SalahAdDin** [comment]
i'll test it.
