### ISSUE TITLE
how to enable multiselect actions in pages that opens in popup windows?

### ISSUE THREAD

**Issue by carlosfvieira** [geex-arts/django-jet#87]
When opening an admin list in a popup window, the column with checkoxes to do multiselection does not appear, and combo with actions is not appearing also...

I've done a search and i«m not finding what exactly how can i enable this... basically it's related with GET var ?_popup=1, but can't find the files i should change/override to change this...

Any ideas? Thanks!

**Comment by SalahAdDin** [comment]
Can you put here a image? We try solve in our fork.

**Comment by carlosfvieira** [comment]
Hi @SalahAdDin here it is:

Normal admin list:
![image](https://cloud.githubusercontent.com/assets/8830610/16787508/b694d984-4894-11e6-9e37-e1d0f818d22e.png)

When calling admin list page, with ?_popup=1 GET parameter (no checkboxes and no action combobox):
![image](https://cloud.githubusercontent.com/assets/8830610/16787544/eea42456-4894-11e6-9fcb-609e44442971.png)

**Comment by SalahAdDin** [comment]
How should be see this?

**Comment by carlosfvieira** [comment]
What do you mean? Multiselection should be available, even when window is
popup...
Em 13/07/2016 02:22, "Yusuf (Josè) Luis" <notifications@github.com>
escreveu:

How should be see this?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/geex-arts/django-jet/issues/87#issuecomment-232229124>,
or mute the thread
<https://github.com/notifications/unsubscribe/AIa-kmE17WFwMbxf-z51kLh-ycwnQyNHks5qVD3LgaJpZM4JJ0xR>
.

**Comment by SalahAdDin** [comment]
A screen shot with normal view, not `django-jet` view.

**Comment by f1nality** [comment]
JET doesn't hide checkboxes for popup views so its normal behavior in Django

**Comment by carlosfvieira** [comment]
Ok thanks @f1nality !
