### ISSUE TITLE
Can't login with django-jet

### ISSUE THREAD

**Issue by arturataide** [geex-arts/django-jet#88]
I've installed django-jet and since then I can't login in Admin Area with valid credencials.

My INSTALLED APPS:

```
INSTALLED_APPS = (
    'jet.dashboard',
    'jet',
    'django.contrib.admin',
     ...)

```
When I remove django-jet from installed apps the default django admin appears and I am able to login. I am also able to login in shell with the `django.contrib.auth.authenticate` function. The user `is_staff` and `is_superuser` variables are ser `True`

With django-jet the login POST request returns a 200 code but it redirects to /admin url without the session being created. I've followed the install steps as recommended in http://jet.readthedocs.io/en/latest/install.html and I'm working with Django 1.6.

I've no idea what it Could be. Thanks

**Comment by SalahAdDin** [comment]
Have you migrate it the app?

'django.template.context_processors.request',` put this in context processors.

**Comment by arturataide** [comment]
Yes @SalahAdDin, I've migrated the app and added the `django.template.context_processors.request` to the settings:
`TEMPLATE_CONTEXT_PROCESSORS = (
    ...
    'django.template.context_processors.request',
)`

Should I create a custom login page?

**Comment by SalahAdDin** [comment]
I think so, but, with the normal admin login page it works, i don't understand what happen with it.

**Comment by arturataide** [comment]
In my other app this is running fine.. I'll analyze the differences between the two config files, but the main difference is django version. Working app is 1.9 and the other is 1.6

**Comment by SalahAdDin** [comment]
But,with the last `django-jet`version we have compatibility with  `django=1.9`. I can login with it.

**Comment by arturataide** [comment]
I've created a login custom page.. I think the issue is with Django 1.6.. Thanks @SalahAdDin

**Comment by SalahAdDin** [comment]
Ok man, if you have problems please say us, and review our fork :+1:

**Comment by f1nality** [comment]
Is this actual for 1.0.0?

**Comment by arturataide** [comment]
@f1nality I have only tested with 0.1.4, if you try with 1.0.0 please let me know if it's ok ;)

**Comment by f1nality** [comment]
@arturataide maybe it was somehow connected with overrided login template (because does not change any login logic). Since 0.9.0 version login template is not overrided, so maybe problem will not appear now. I personally use JET for a single Django 1.6 project since about 0.0.9 version and there was no problem for me with login page. Therefore, it is some specific case.

**Comment by f1nality** [comment]
Should be OK with 0.9.0+. I reproduced problem with Django 1.6 with older JET versions.
