### ISSUE TITLE
custom admin site module

### ISSUE THREAD

**Issue by sysint64** [geex-arts/django-jet#89]
I have 2 custom admin module: `uplevel_admin` and `lowerlevel_admin`. With default admin `admin.site` all works fine, but with my custom admins site crashes with an error:
`Reverse for 'app_list' with arguments '()' and keyword arguments '{'app_label': 'auth'}' not found. 1 pattern(s) tried: ['admin/(?P<app_label>filer|ads|news|articles|cities)/$']`

**Comment by f1nality** [comment]
Fixed in 1.0.0

**Comment by danielquinn** [comment]
@f1nality how (and where) did you fix it?  I'm having a dreadful (but similar) problem with another package and could use some pointers.

**Comment by expresspotato** [comment]
This problem happens for me when the app doesn't have an admin.py file and defining admin classes... Super annoying as I don't need package models to be included in the admin (namely in my case django-cities-light).

**Comment by XploitXploit** [comment]
still not fixed!!
