### ISSUE TITLE
jet-dashboard seems to not be enabled

### ISSUE THREAD

**Issue by blueicefield** [geex-arts/django-jet#9]
Hi, 
First all, I would like to thank you for this beautiful admin.
I have tried to enable the `jet dashboard` following the readme on the release 0.9 but that does not seems to work. 

I dont see the widget field on the top right corner, I haven't also the `Hide applications` collapse on the sidebar.

My settings : 

```python
# settings.py
INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'modeltranslation',
    'jet.dashboard',
    'jet',
    'django.contrib.admin',
    'compressor',
    'naomi',
    'django_extensions',
    'redactor',
    'cv',
]
```

```python
# urls.py
urlpatterns = patterns('',
    url(r'^$', lambda r : HttpResponseRedirect('cv/')),
    url(r'^jet/', include('jet.urls', 'jet')),
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^redactor/', include('redactor.urls')),
    url(r'^robots.txt$', lambda r: HttpResponse("User-agent: *\nDisallow: /", content_type="text/plain")),
)
```

My python packages:
```
Django (1.8.4)
django-appconf (1.0.1)
django-compressor (1.5)
django-extensions (1.5.6)
django-jet (0.0.9)
django-modeltranslation (0.10.1)
django-naomi (0.8)
django-wysiwyg-redactor (0.4.9)
ecdsa (0.13)
Fabric (1.10.2)
google-api-python-client (1.4.2)
httplib2 (0.9.1)
oauth2client (1.5.1)
paramiko (1.15.2)
Pillow (2.9.0)
pip (7.1.2)
pyasn1 (0.1.8)
pyasn1-modules (0.0.7)
pycrypto (2.6.1)
rsa (3.2)
setuptools (18.3.1)
simplejson (3.8.0)
six (1.9.0)
uritemplate (0.6)
Werkzeug (0.10.4)
wheel (0.25.0)
```

Any idea about this problem ?

**Comment by mightygraf** [comment]
Hi,
Thank you for your response and report!
Yes, I can confirm its 0.0.9 issue. Fix will arrive apparently today.

**Comment by mightygraf** [comment]
0.1.0 is released, it should fix your problem

**Comment by blueicefield** [comment]
@mightygraf: With de 0.1.0 the dashboard is displayed but the widget for Google analytics is not present in the `widget dropdown`... may be it is normal ?!

**Comment by denis-kildishev** [comment]
Yes, dashboard documentation is pretty bad at the moment. I will update it soon. 
Full demo site source code is available here https://github.com/geex-arts/django-jet-demo.

In fact all you need is:

1. Define your custom dashboard like here:
https://github.com/geex-arts/django-jet-demo/blob/master/dashboard.py

2. Set dashboard path in settings
JET_INDEX_DASHBOARD = 'dashboard.CustomIndexDashboard'
JET_APP_INDEX_DASHBOARD = 'dashboard.CustomAppIndexDashboard'
3. Thats all. Note that Google Analytics widgets will also require

pip install google-api-python-client

and 

JET_MODULE_GOOGLE_ANALYTICS_CLIENT_SECRETS_FILE in your settings.py
it should contain path to your google analytics client secrents json file
