### ISSUE TITLE
Some problems with static files

### ISSUE THREAD

**Issue by SalahAdDin** [geex-arts/django-jet#92]
I can see these bug in the change form list:
![seleccion_133](https://cloud.githubusercontent.com/assets/5034215/17127709/451ade64-52cd-11e6-97cf-87e6cb9b16a7.png)

So, i try view if we have problem in browser console and i can found this:
![seleccion_132](https://cloud.githubusercontent.com/assets/5034215/17127720/5b291ff4-52cd-11e6-94d2-995e6c74185c.png)

The same bug with image-gif file. Didn't solved yet.

**Comment by f1nality** [comment]
What's wrong with the first screenshot? I can't see any bugs.
jquery-ui, timepicker and select2 don't have es-CO locale, only es. Is it greatly differs from es-CO?

**Comment by SalahAdDin** [comment]
I can see one, red circle, is the same that django admin template by default, if i don't wrong django jet chage it by checklist without circle.

**Comment by f1nality** [comment]
Yes, it's django 1.9+ related bug. I'll fix it, it's not connected with missing locales.

**Comment by SalahAdDin** [comment]
Ah, so ok.

I'd propoused change jquery-datepicker with date dropper, use a easier language date handled way.

**Comment by f1nality** [comment]
0.9.0 checks locales files for existance and tries less specific locales if possible ("es" instead of "es-CO" if it doesn't exist).
