### ISSUE TITLE
jet\templates\admin\base.html : ?v={{ JET_VERSION }}" appended to generated static URL breaks when reading files from Amazon S3 static deployment

### ISSUE THREAD

**Issue by kbruner32** [geex-arts/django-jet#93]
The generated URL looks like this...

- https://[bucket].s3.amazonaws.com/static/jet/css/icons/style.css?Signature=[SIG]&Expires=1501109158&AWSAccessKeyId=[KEY]?v=0.1.5

\<Error\>
\<Code\>InvalidAccessKeyId\</Code\>
\<Message\>
The AWS Access Key Id you provided does not exist in our records.
\</Message\>
\</Error\>

===============================================

If the URL was constructed assuming not the first URL parameter with & instead of ? 

- https://[bucket].s3.amazonaws.com/static/jet/css/icons/style.css?Signature=[SIG]&Expires=1501109158&AWSAccessKeyId=[KEY]&v=0.1.5

then it works.

===============================================

.virtualenvs\[projectname]\Lib\site-packages\jet\templates\admin\base.html:

   15:     \<link href="{% static "jet/css/icons/style.css" %}?v={{ JET_VERSION }}" rel="stylesheet" />
   16:     \<link href="{% static "jet/css/themes/"|add:THEME|add:"/base.css" %}?v={{ JET_VERSION }}" rel="stylesheet" class="base-stylesheet" />
   17:     \<link href="{% static "jet/css/themes/"|add:THEME|add:"/select2.theme.css" %}?v={{ JET_VERSION }}" rel="stylesheet" class="select2-stylesheet" />
   18:     \<link href="{% static "jet/css/themes/"|add:THEME|add:"/jquery-ui.theme.css" %}?v={{ JET_VERSION }}" rel="stylesheet" class="jquery-ui-stylesheet" />
   53:     \<script src="{% static "jet/js/main.min.js" %}?v={{ JET_VERSION }}"></script>
   54:     \<script src="{% static "jet/js/select2.jet.min.js" %}?v={{ JET_VERSION }}"></script>

   88:    data-base-stylesheet="{% static "jet/css/themes/"|add:conf_theme.theme|add:"/base.css" %}?v={{ JET_VERSION }}"
   89:    data-select2-stylesheet="{% static "jet/css/themes/"|add:conf_theme.theme|add:"/select2.theme.css" %}?v={{ JET_VERSION }}"
   90:    data-jquery-ui-stylesheet="{% static "jet/css/themes/"|add:conf_theme.theme|add:"/jquery-ui.theme.css" %}?v={{ JET_VERSION }}"

**Comment by f1nality** [comment]
Fixed in 0.9.1
