### ISSUE TITLE
Change login.html name 'ADMIN SITE'

### ISSUE THREAD

**Issue by sagoyanfisic** [geex-arts/django-jet#97]
<body class=" login">
    
    <div class="login-title">
        <span class="bright">Admin</span> Site
    </div>

    <div class="login-container" id="content-main">
        <div class="login-container-header">
            Iniciar sesión
        </div>
        <div class="login-container-content">
            <form action="/admin/login/?next=/admin/" method="post" class="login-form" id="login-form"><input type='hidden' name='csrfmiddlewaretoken' value='zfvLi5tbuH1NsXovHtVDbtvkje57t8la' />

**Comment by SalahAdDin** [comment]
Eh?

**Comment by f1nality** [comment]
@sagoyanfisic do you mean there is not localization for this label? New JET version will not contain this label, so not translation will be needed.

**Comment by SalahAdDin** [comment]
@f1nality Could we add this label?

**Comment by f1nality** [comment]
@SalahAdDin 
I have answered it here https://github.com/geex-arts/django-jet/issues/23

**Comment by f1nality** [comment]
0.9.0 doesn't have this label.
