### ISSUE TITLE
Wrong dashboard settings documentation

### ISSUE THREAD

**Issue by SalahAdDin** [geex-arts/django-jet#98]
Hi, i'm working in a project and i set the other questions:
```python
JET_INDEX_DASHBOARD = 'jet.dashboard.DefaultIndexDashboard'

JET_APP_INDEX_DASHBOARD = 'jet.dashboard.DefaultAppIndexDashboard'
```

Put this settings in my settings file and i get this problem:
![attributeerror at -admin- - mozilla firefox_154](https://cloud.githubusercontent.com/assets/5034215/17541287/8269c4a8-5e83-11e6-9223-eb66dcb0f2c7.png)

Then, i investigated in the code and i change the settings to this:
```python
JET_INDEX_DASHBOARD = 'jet.dashboard.dashboard.DefaultIndexDashboard'

JET_APP_INDEX_DASHBOARD = 'jet.dashboard.dashboard.DefaultAppIndexDashboard'
```

And this fixes this bug.

In addition, the violet theme doesn't works anymore, can you get back it? or delete it from documentation files.

**Comment by f1nality** [comment]
Thanks, will be fixed. Violet theme should be deleted, it was a in-development theme.

**Comment by SalahAdDin** [comment]
Can i help with this themes?

**Comment by f1nality** [comment]
It didn't turn into something nice, so only if some new themes can be added. But I don't have any ideas yet.

**Comment by SalahAdDin** [comment]
I have other colors as ideas.

**Comment by f1nality** [comment]
Documentation updated in 0.9.1
