### ISSUE TITLE
Django Treebeard template bug

### ISSUE THREAD

**Issue by SalahAdDin** [geex-arts/django-jet#99]
Hi guys, i'm using a project that use `django-treebeard` as requirement, and when i go to his models i get this style issue:
![seleccion_160](https://cloud.githubusercontent.com/assets/5034215/17640956/97014494-60d2-11e6-86f7-6e5e9369ca88.png)

![seleccion_174](https://cloud.githubusercontent.com/assets/5034215/17640963/c3d20d82-60d2-11e6-834d-4bfd033297b2.png)

How can we solve this issue?

**Comment by f1nality** [comment]
Have you tried it with feature/relayout branch? As it doesn't make so many modifications to layout , it could look better.

**Comment by SalahAdDin** [comment]
I'm waiting for the official release.

**Comment by f1nality** [comment]
0.9.0 released

**Comment by SalahAdDin** [comment]
Thank you man!!!

**Comment by f1nality** [comment]
> Did you forget make my pr?

I didn't, there is a problem with it https://github.com/geex-arts/django-jet/pull/91

**Comment by SalahAdDin** [comment]
Ok man, for now doesn't merge, i'll update my fork and make these change and add the migration file :D

**Comment by Ismael-VC** [comment]
Please come to the django-jet Discord server so we can organize if you like:

  *   https://discord.gg/3yr5yeH

Welcome! 😄

**Comment by SalahAdDin** [comment]
@f1nality It seems solved now.
